Repository Kernel360/F2-BIENGUAL-BE, pull requests merged in 2024-09, with the labels that each got.

#8 [FEAT] : Default Setting
  .gitignore
  build.gradle
  docker-compose.yml
  settings.gradle
  src/main/java/com/echall/platform/EnglishChallengePlatformApplication.java
  src/main/java/com/echall/platform/config/SwaggerConfig.java
  src/main/resources/application.yml
  src/main/resources/yml/application-dev.yml
  src/main/resources/yml/application-local.yml
  src/main/resources/yml/application-prod.yml
  src/main/resources/yml/logging/application-log.yml
  src/test/java/com/echall/platform/EnglishChallengePlatformApplicationTests.java
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, ⚙️ SETTING, 🌚 BE

#11 [FEAT]: Pair Programming for Code Convention
  build.gradle
  src/main/java/com/echall/platform/user/controller/UserApiController.java
  src/main/java/com/echall/platform/user/controller/UserPublicController.java
  src/main/java/com/echall/platform/user/domain/dto/UserRequestDto.java
  src/main/java/com/echall/platform/user/domain/dto/UserResponseDto.java
  src/main/java/com/echall/platform/user/domain/entity/BaseEntity.java
  src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
  src/main/java/com/echall/platform/user/domain/enums/Gender.java
  src/main/java/com/echall/platform/user/domain/enums/Role.java
  src/main/java/com/echall/platform/user/domain/enums/UserStatus.java
  src/main/java/com/echall/platform/user/repository/UserRepository.java
  src/main/java/com/echall/platform/user/repository/custom/UserRepositoryCustom.java
  src/main/java/com/echall/platform/user/repository/custom/UserRepositoryImpl.java
  src/main/java/com/echall/platform/user/service/UserService.java
Labels: 🦋 MJ, 🐶 YR, 🦊 TJ, 📑 DOCS, ⚙️ SETTING, 🌚 BE

#13 [FEAT] : User CRUD Initial version
  build.gradle
  src/main/generated/com/echall/platform/user/domain/entity/QBaseEntity.java
  src/main/generated/com/echall/platform/user/domain/entity/QUserEntity.java
  src/main/java/com/echall/platform/user/controller/UserApiController.java
  src/main/java/com/echall/platform/user/domain/dto/UserRequestDto.java
  src/main/java/com/echall/platform/user/domain/dto/UserResponseDto.java
  src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
  src/main/java/com/echall/platform/user/domain/enums/UserStatus.java
  src/main/java/com/echall/platform/user/repository/UserRepository.java
  src/main/java/com/echall/platform/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/templates/naver-intellij-formatter.xml
  src/main/resources/yml/application-local.yml
Labels: ✨ FEAT, 🐶 YR, 🔖 HIGH, 🌚 BE

#14 [FEAT] : 기본적인 customException 생성
  src/main/java/com/echall/platform/exception/challenge/ApiChallengeErrorSubCategory.java
  src/main/java/com/echall/platform/exception/challenge/ApiChallengeException.java
  src/main/java/com/echall/platform/exception/common/ApiErrorCategory.java
  src/main/java/com/echall/platform/exception/common/ApiErrorResponse.java
  src/main/java/com/echall/platform/exception/common/ApiErrorSubCategory.java
  src/main/java/com/echall/platform/exception/common/ApiException.java
  src/main/java/com/echall/platform/exception/common/ApiExceptionHandler.java
  src/main/java/com/echall/platform/exception/content/ApiContentErrorSubCategory.java
  src/main/java/com/echall/platform/exception/content/ApiContentException.java
  src/main/java/com/echall/platform/exception/review/ApiReviewErrorSubCategory.java
  src/main/java/com/echall/platform/exception/review/ApiReviewException.java
  src/main/java/com/echall/platform/exception/user/ApiUserErrorSubCategory.java
  src/main/java/com/echall/platform/exception/user/ApiUserException.java
Labels: ✨ FEAT, 🦊 TJ, 🔖 LOW, 🌚 BE

#15 [FEAT] 학습 콘텐츠 로직 추가
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/echall/platform/EnglishChallengePlatformApplication.java
  src/main/java/com/echall/platform/config/JpaConfig.java
  src/main/java/com/echall/platform/config/MongoConfig.java
  src/main/java/com/echall/platform/content/controller/ContentApiController.java
  src/main/java/com/echall/platform/content/controller/ContentPublicController.java
  src/main/java/com/echall/platform/content/domain/dto/ContentPageResponse.java
  src/main/java/com/echall/platform/content/domain/dto/ContentRequestDto.java
  src/main/java/com/echall/platform/content/domain/dto/ContentResponseDto.java
  src/main/java/com/echall/platform/content/domain/dto/ContentUpdateRequestDto.java
  src/main/java/com/echall/platform/content/domain/entity/ContentEntity.java
  src/main/java/com/echall/platform/content/domain/entity/MongoBaseEntity.java
  src/main/java/com/echall/platform/content/domain/enums/ContentStatus.java
  src/main/java/com/echall/platform/content/domain/enums/ContentType.java
  src/main/java/com/echall/platform/content/repository/ContentRepository.java
  src/main/java/com/echall/platform/content/service/ContentService.java
  src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/yml/application-local.yml
Labels: ✨ FEAT, 🦋 MJ, 🐞 BUGFIX, 🔖 MEDIUM, 🌚 BE

#17 [feat] 카테고리 로직 추가 #16
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/echall/platform/EnglishChallengePlatformApplication.java
  src/main/java/com/echall/platform/category/controller/CategoryApiController.java
  src/main/java/com/echall/platform/category/controller/CategoryPublicController.java
  src/main/java/com/echall/platform/category/domain/dto/CategoryRequestDto.java
  src/main/java/com/echall/platform/category/domain/dto/CategoryResponseDto.java
  src/main/java/com/echall/platform/category/domain/entity/CategoryEntity.java
  src/main/java/com/echall/platform/category/repository/CategoryRepository.java
  src/main/java/com/echall/platform/category/service/CategoryService.java
  src/main/java/com/echall/platform/category/service/CategoryServiceImpl.java
  src/main/java/com/echall/platform/config/JpaConfig.java
  src/main/java/com/echall/platform/config/MongoConfig.java
  src/main/java/com/echall/platform/content/controller/ContentApiController.java
  src/main/java/com/echall/platform/content/controller/ContentPublicController.java
  src/main/java/com/echall/platform/content/domain/dto/ContentPageResponse.java
  src/main/java/com/echall/platform/content/domain/dto/ContentRequestDto.java
  src/main/java/com/echall/platform/content/domain/dto/ContentResponseDto.java
  src/main/java/com/echall/platform/content/domain/dto/ContentUpdateRequestDto.java
  src/main/java/com/echall/platform/content/domain/entity/ContentEntity.java
  src/main/java/com/echall/platform/content/domain/entity/MongoBaseEntity.java
  src/main/java/com/echall/platform/content/domain/enums/ContentStatus.java
  src/main/java/com/echall/platform/content/domain/enums/ContentType.java
  src/main/java/com/echall/platform/content/repository/ContentRepository.java
  src/main/java/com/echall/platform/content/service/ContentService.java
  src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/yml/application-local.yml
Labels: ✨ FEAT, 🦋 MJ, 🐞 BUGFIX, 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE

#19 [FEAT] : Spring Security & OAuth2
  .github/pull_request_template.md
  .gitignore
  build.gradle
  docker-compose.yml
  src/main/generated/com/echall/platform/oauth2/domain/entity/QRefreshToken.java
  src/main/generated/com/echall/platform/user/domain/entity/QUserEntity.java
  src/main/java/com/echall/platform/EnglishChallengePlatformApplication.java
  src/main/java/com/echall/platform/category/controller/CategoryApiController.java
  src/main/java/com/echall/platform/category/controller/CategoryPublicController.java
  src/main/java/com/echall/platform/category/domain/dto/CategoryRequestDto.java
  src/main/java/com/echall/platform/category/domain/dto/CategoryResponseDto.java
  src/main/java/com/echall/platform/category/domain/entity/CategoryEntity.java
  src/main/java/com/echall/platform/category/repository/CategoryRepository.java
  src/main/java/com/echall/platform/category/service/CategoryService.java
  src/main/java/com/echall/platform/category/service/CategoryServiceImpl.java
  src/main/java/com/echall/platform/config/MongoConfig.java
  src/main/java/com/echall/platform/config/PasswordEncoderConfig.java
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/config/TokenAuthenticationFilter.java
  src/main/java/com/echall/platform/content/controller/ContentApiController.java
  src/main/java/com/echall/platform/content/controller/ContentPublicController.java
  src/main/java/com/echall/platform/content/domain/dto/ContentPageResponse.java
  src/main/java/com/echall/platform/content/domain/dto/ContentRequestDto.java
  src/main/java/com/echall/platform/content/domain/dto/ContentResponseDto.java
  src/main/java/com/echall/platform/content/domain/dto/ContentUpdateRequestDto.java
  src/main/java/com/echall/platform/content/domain/entity/ContentEntity.java
  src/main/java/com/echall/platform/content/domain/entity/MongoBaseEntity.java
  src/main/java/com/echall/platform/content/domain/enums/ContentStatus.java
  src/main/java/com/echall/platform/content/domain/enums/ContentType.java
  src/main/java/com/echall/platform/content/repository/ContentRepository.java
  src/main/java/com/echall/platform/content/service/ContentService.java
  src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
  src/main/java/com/echall/platform/oauth2/JwtProperties.java
  src/main/java/com/echall/platform/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/echall/platform/oauth2/TokenProvider.java
  src/main/java/com/echall/platform/oauth2/controller/TokenApiController.java
  src/main/java/com/echall/platform/oauth2/domain/GoogleUserInfo.java
  src/main/java/com/echall/platform/oauth2/domain/OAuth2UserInfo.java
  src/main/java/com/echall/platform/oauth2/domain/dto/TokenDto.java
  src/main/java/com/echall/platform/oauth2/domain/entity/RefreshToken.java
  src/main/java/com/echall/platform/oauth2/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/echall/platform/oauth2/repository/RefreshTokenRepository.java
  src/main/java/com/echall/platform/oauth2/service/OAuth2UserCustomService.java
  src/main/java/com/echall/platform/oauth2/service/RefreshTokenService.java
  src/main/java/com/echall/platform/oauth2/service/TokenService.java
  src/main/java/com/echall/platform/user/controller/UserApiController.java
  src/main/java/com/echall/platform/user/controller/UserPublicController.java
  src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
  src/main/java/com/echall/platform/user/service/UserService.java
  src/main/java/com/echall/platform/util/CookieUtil.java
  src/main/java/com/echall/platform/util/RandomNicknameGenerator.java
  src/main/resources/application.yml
  src/main/resources/static/favicon.ico
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
  src/main/resources/yml/application-local.yml
Labels: ✨ FEAT, 🦋 MJ, 🐶 YR, 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE

#21 [Refactor] 1차 배포 전 custom exception 추가 #20 (진행중)..
  docker-compose.yml
  src/main/java/com/echall/platform/exception/category/CategoryNotFoundException.java
  src/main/java/com/echall/platform/exception/category/InvalidCategoryException.java
  src/main/java/com/echall/platform/exception/challenge/ApiChallengeErrorSubCategory.java
  src/main/java/com/echall/platform/exception/challenge/ApiChallengeException.java
  src/main/java/com/echall/platform/exception/common/ApiErrorCategory.java
  src/main/java/com/echall/platform/exception/common/ApiErrorResponse.java
  src/main/java/com/echall/platform/exception/common/ApiErrorSubCategory.java
  src/main/java/com/echall/platform/exception/common/ApiException.java
  src/main/java/com/echall/platform/exception/common/ApiExceptionHandler.java
  src/main/java/com/echall/platform/exception/common/ErrorCode.java
  src/main/java/com/echall/platform/exception/common/ErrorResponse.java
  src/main/java/com/echall/platform/exception/common/GlobalExceptionHandler.java
  src/main/java/com/echall/platform/exception/content/ApiContentErrorSubCategory.java
  src/main/java/com/echall/platform/exception/content/ApiContentException.java
  src/main/java/com/echall/platform/exception/review/ApiReviewErrorSubCategory.java
  src/main/java/com/echall/platform/exception/review/ApiReviewException.java
  src/main/java/com/echall/platform/exception/user/ApiUserErrorSubCategory.java
  src/main/java/com/echall/platform/exception/user/ApiUserException.java
  src/main/java/com/echall/platform/exception/user/UserNotFoundException.java
  src/main/java/com/echall/platform/exception/user/oauth2/RefreshTokenNotFoundException.java
  src/main/java/com/echall/platform/oauth2/service/RefreshTokenService.java
  src/main/java/com/echall/platform/user/controller/UserPublicController.java
  src/main/resources/application.yml
  src/main/resources/yml/application-local.yml
Labels: 🦋 MJ, 🪨 DEPLOY, 🔖 CRITICAL, ⚒️ REFACTOR, 🌚 BE

#22 [FEAT] : Social Login - Add Platforms
  .gitignore
  build.gradle
  src/main/generated/com/echall/platform/category/domain/entity/QCategoryEntity.java
  src/main/java/com/echall/platform/config/P6SpySqlFormatter.java
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/oauth2/domain/GoogleUserInfo.java
  src/main/java/com/echall/platform/oauth2/domain/KakaoUserInfo.java
  src/main/java/com/echall/platform/oauth2/domain/NaverUserInfo.java
  src/main/java/com/echall/platform/oauth2/service/OAuth2UserCustomService.java
  src/main/java/com/echall/platform/user/controller/UserPublicController.java
  src/main/java/com/echall/platform/user/service/UserService.java
  src/main/resources/templates/login.html
Labels: ✨ FEAT, 🐶 YR, 🔖 LOW, 🌚 BE

#24 [FEAT] : Analyze Data for setting difficulty and Visualization
  WordAnalyzer.py
Labels: 🐶 YR, 🔖 MEDIUM, 🌚 BE

#27 [TEST] : User Service 테스트 코드 추가
  src/main/java/com/echall/platform/user/service/UserService.java
  src/test/java/com/echall/platform/user/controller/UserApiControllerTest.java
  src/test/java/com/echall/platform/user/service/UserServiceTest.java
Labels: 🦊 TJ, ✅ TEST, 🌚 BE

#26 [REFACTOR] : Refactor about OAuth2-Naver and Swagger
  build.gradle
  src/main/java/com/echall/platform/config/SwaggerConfig.java
  src/main/java/com/echall/platform/oauth2/controller/TokenApiController.java
  src/main/java/com/echall/platform/oauth2/domain/NaverUserInfo.java
  src/main/java/com/echall/platform/oauth2/service/OAuth2UserCustomService.java
Labels: ✨ FEAT, 🐶 YR, 🔖 LOW, 🌚 BE

#29 [FEAT] : workflow 설정
  .github/workflows/deploy.yml
Labels: 🦊 TJ, 🪨 DEPLOY, 🔖 HIGH, ⚙️ SETTING, 🌚 BE

#30 [FEAT]: PreProcess and Genrator Questions
  CalculatorQuestionDifficulty.py
  GenerateContentMatchingQuestions.py
  GenerateFIBQuestions.py
  GenerateWordQuestions.py
  PreProcess.py
  packages.py
Labels: ✨ FEAT, 🐶 YR, 🔖 LOW, 🌚 BE

#31 [REFACTOR] : refactor for generating more accurate problems
  GenerateFIBQuestions.py
  GenerateWordQuestions.py
Labels: 🐶 YR, ⚒️ REFACTOR, 🌚 BE

#32 [FIX] : 초기 설정 변경
  .gitignore
  src/main/java/com/echall/platform/oauth2/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/resources/application.yml
  src/main/resources/yml/application-dev.yml
  src/main/resources/yml/application-local.yml
Labels: 🦊 TJ, 🪨 DEPLOY, ⚙️ SETTING, 🌚 BE

#33 [DOCS] : 배포 시 실행 할 스크립트 작성
  appspec.yml
  scripts/start.sh
  scripts/stop.sh
Labels: 🦊 TJ, 📑 DOCS, 🪨 DEPLOY, ⚙️ SETTING, 🌚 BE

#37 [FIX] : deploy.yml
  .github/workflows/deploy.yml
Labels: 🦊 TJ, 🪨 DEPLOY, 🌚 BE

#39 [BUGFIX] : deploy.yml 테스트코드 무시 명령어 추가
  .github/workflows/deploy.yml
Labels: 🌚 BE

#35 [DOCS] 앞으로 구현해야 할 멀티 모듈 관련 사항
  multi-module.excalidraw
  multi-module.jpg
Labels: 📑 DOCS, 🔖 LOW, 🌚 BE

#43 Workflow를 위한 Dockerfile 생성
  Dockerfile
Labels: 🦊 TJ, 🪨 DEPLOY, 🌚 BE

#42 [FIX] : CI/CD 설정 파일 수정
  .github/workflows/deploy.yml
  appspec.yml
  scripts/start.sh
  scripts/stop.sh
  src/main/resources/application.yml
  src/main/resources/yml/application-prod.yml
Labels: 🦊 TJ, 🐞 BUGFIX, 🪨 DEPLOY, 🔖 MEDIUM, ⚙️ SETTING, 🌚 BE

#44 [FEAT] Bookmark 기능 추가
  src/main/java/com/echall/platform/bookmark/controller/BookmarkApiController.java
  src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkRequestDto.java
  src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkResponseDto.java
  src/main/java/com/echall/platform/bookmark/domain/entity/BookmarkEntity.java
  src/main/java/com/echall/platform/bookmark/repository/BookmarkRepository.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkService.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/echall/platform/content/controller/ContentPublicController.java
  src/main/java/com/echall/platform/content/domain/enums/SearchCondition.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
  src/main/java/com/echall/platform/content/service/ContentService.java
  src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
  src/main/java/com/echall/platform/user/controller/UserApiController.java
  src/main/java/com/echall/platform/user/controller/UserPublicController.java
  src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#53 [FEAT] YouTube Crawler by using API & Selenium
  build.gradle
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/config/YoutubeAppConfig.java
  src/main/java/com/echall/platform/content/controller/ContentApiController.java
  src/main/java/com/echall/platform/crawling/controller/CrawlingController.java
  src/main/java/com/echall/platform/crawling/domain/dto/CrawlingRequestDto.java
  src/main/java/com/echall/platform/crawling/domain/dto/CrawlingResponseDto.java
  src/main/java/com/echall/platform/crawling/service/CrawlingService.java
  src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
  src/main/java/com/echall/platform/util/CookieUtil.java
  src/main/resources/application.yml
Labels: ✨ FEAT, 🐶 YR, 🔖 LOW, 🌚 BE

#54 [REFACTORING] Crawling 과정 Content Create 로 통합
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/content/controller/ContentApiController.java
  src/main/java/com/echall/platform/content/domain/dto/ContentRequestDto.java
  src/main/java/com/echall/platform/content/domain/dto/ContentResponseDto.java
  src/main/java/com/echall/platform/content/domain/entity/ContentDocument.java
  src/main/java/com/echall/platform/content/domain/entity/ContentEntity.java
  src/main/java/com/echall/platform/content/domain/entity/Script.java
  src/main/java/com/echall/platform/content/domain/enums/ContentType.java
  src/main/java/com/echall/platform/content/repository/ContentRepository.java
  src/main/java/com/echall/platform/content/repository/ContentScriptRepository.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
  src/main/java/com/echall/platform/content/service/ContentService.java
  src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
  src/main/java/com/echall/platform/crawling/controller/CrawlingController.java
  src/main/java/com/echall/platform/crawling/domain/dto/CrawlingResponseDto.java
  src/main/java/com/echall/platform/crawling/service/CrawlingService.java
  src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
Labels: 🐶 YR, 🔖 LOW, ⚒️ REFACTOR, 🌚 BE
