Repository Kernel360/F2-BIENGUAL-BE, pull requests merged in 2024-10, with the labels that each got.

#67 [SETTING] Nginx 설정
  .gitignore
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/config/SwaggerConfig.java
  src/main/java/com/echall/platform/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/echall/platform/oauth2/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/echall/platform/user/controller/UserPublicController.java
  src/main/java/com/echall/platform/util/CookieUtil.java
  src/main/resources/application.yml
  src/main/resources/yml/application-local.yml
  src/main/resources/yml/application-prod.yml
Labels: 🪨 DEPLOY, 🔖 MEDIUM, ⚒️ REFACTOR, ⚙️ SETTING, 🌚 BE

#74 [SETTING] deploy.yml, Dockerfile 변경
  .github/workflows/deploy.yml
  Dockerfile
Labels: 🪨 DEPLOY, 🔖 HIGH, 🌚 BE, 🏀 CW

#75 [HOTFIX] application-local.yml, application-prod.yml 구글 리다이렉트 uri 삭제
  src/main/resources/yml/application-local.yml
  src/main/resources/yml/application-prod.yml
Labels: 🪨 DEPLOY, 🔖 HIGH, 🌚 BE, 🏀 CW

#77 [SETTING] https 환경을 위한 쿠키 설정
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/config/WebConfig.java
  src/main/java/com/echall/platform/oauth2/OAuth2FailureHandler.java
  src/main/java/com/echall/platform/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/echall/platform/util/CookieUtil.java
  src/main/resources/yml/application-local.yml
  src/main/resources/yml/application-prod.yml
Labels: 🔖 HIGH, ⚒️ REFACTOR, ⚙️ SETTING, 🌚 BE, 🏀 CW

#78 [FIX] 쿠키 domain 설정 변경
  src/main/java/com/echall/platform/util/CookieUtil.java
Labels: 🐞 BUGFIX, 🔖 HIGH, 🌚 BE, 🏀 CW

#79 [FIX] Cors 설정 Origin 추가
  src/main/java/com/echall/platform/config/WebConfig.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#81 [HOTFIX] 스프링부트 Cors 설정하는 객체 변경
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/config/WebConfig.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#86 [TEST] 시연을 위한 cors 설정
  src/main/java/com/echall/platform/config/SecurityConfig.java
Labels: 🔖 CRITICAL, ✅ TEST, 🌚 BE, 🏀 CW

#87 [FEAT] 파이썬의 deep_translator를 이용한 번역 기능 추가
  .gitignore
  src/main/java/com/echall/platform/bookmark/controller/BookmarkApiController.java
  src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkRequestDto.java
  src/main/java/com/echall/platform/bookmark/domain/entity/BookmarkEntity.java
  src/main/java/com/echall/platform/config/MongoConfig.java
  src/main/java/com/echall/platform/content/domain/entity/Script.java
  src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
  src/main/java/com/echall/platform/crawling/bot/CalculatorQuestionDifficulty.py
  src/main/java/com/echall/platform/crawling/bot/GenerateContentMatchingQuestions.py
  src/main/java/com/echall/platform/crawling/bot/GenerateFIBQuestions.py
  src/main/java/com/echall/platform/crawling/bot/GenerateWordQuestions.py
  src/main/java/com/echall/platform/crawling/bot/PreProcess.py
  src/main/java/com/echall/platform/crawling/bot/Translator.py
  src/main/java/com/echall/platform/crawling/bot/WordAnalyzer.py
  src/main/java/com/echall/platform/crawling/bot/packages.py
  src/main/java/com/echall/platform/crawling/service/CrawlingService.java
  src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
  src/main/java/com/echall/platform/message/error/code/CrawlingErrorCode.java
  src/main/java/com/echall/platform/message/status/CrawlingServiceStatus.java
  src/main/resources/yml/application-local.yml
Labels: ✨ FEAT, 🐶 YR, 🔖 LOW, ⚒️ REFACTOR, 🌚 BE

#89 [REFACTOR] 배포 워크플로우 dev와 prod 수정
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#90 [REFACTOR] 배포 워크플로우 dev와 prod 수정 2차
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#91 [REFACTOR] 배포 워크플로우 dev와 prod 수정 3차
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#92 [REFACTOR] 배포 워크플로우 dev와 prod 수정 4차
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#93 [BUGFIX] Dockerfile 수정
  Dockerfile
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#94 [BUGFIX] Dockerfile 수정 2차
  Dockerfile
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#95 Bugfix: dev prod 워크플로우 수정 6차
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#97 [REFACTOR] Microsoft Azure AI Translator 로 번역 방식 수정
  build.gradle
  src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
  src/main/java/com/echall/platform/crawling/service/TranslateService.java
  src/main/java/com/echall/platform/message/error/code/CrawlingErrorCode.java
  src/main/resources/application.yml
Labels: ✨ FEAT, 🐶 YR, 🔖 LOW, ⚒️ REFACTOR, 🌚 BE

#98 [REFACTOR] 소셜 로그인 로직 및 인증 로직 리팩토링
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/config/TokenAuthenticationFilter.java
  src/main/java/com/echall/platform/message/error/code/TokenErrorCode.java
  src/main/java/com/echall/platform/message/error/code/UserErrorCode.java
  src/main/java/com/echall/platform/message/error/exception/OAuth2AuthenticationProcessingException.java
  src/main/java/com/echall/platform/message/status/TokenServiceStatus.java
  src/main/java/com/echall/platform/message/status/UserServiceStatus.java
  src/main/java/com/echall/platform/oauth2/AccessDeniedHandlerImpl.java
  src/main/java/com/echall/platform/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/echall/platform/oauth2/TokenProvider.java
  src/main/java/com/echall/platform/oauth2/domain/entity/RefreshToken.java
  src/main/java/com/echall/platform/oauth2/domain/enums/OAuth2Provider.java
  src/main/java/com/echall/platform/oauth2/domain/info/GoogleUserInfo.java
  src/main/java/com/echall/platform/oauth2/domain/info/KakaoUserInfo.java
  src/main/java/com/echall/platform/oauth2/domain/info/NaverUserInfo.java
  src/main/java/com/echall/platform/oauth2/domain/info/OAuth2UserInfo.java
  src/main/java/com/echall/platform/oauth2/domain/info/OAuth2UserInfoFactory.java
  src/main/java/com/echall/platform/oauth2/domain/info/OAuth2UserPrincipal.java
  src/main/java/com/echall/platform/oauth2/service/OAuth2UserCustomService.java
  src/main/java/com/echall/platform/oauth2/service/RefreshTokenService.java
  src/main/java/com/echall/platform/oauth2/service/TokenService.java
  src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
  src/main/java/com/echall/platform/user/repository/UserRepository.java
  src/main/java/com/echall/platform/user/service/UserService.java
  src/main/java/com/echall/platform/util/CookieUtil.java
  src/main/java/com/echall/platform/util/HttpServletResponseUtil.java
  src/main/resources/application.yml
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#104 [REFACTOR] 북마크 리팩토링 및 일부 기능 추가
  src/main/java/com/echall/platform/bookmark/controller/BookmarkApiController.java
  src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkRequestDto.java
  src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkResponseDto.java
  src/main/java/com/echall/platform/bookmark/domain/entity/BookmarkEntity.java
  src/main/java/com/echall/platform/bookmark/repository/BookmarkRepository.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkService.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/echall/platform/content/controller/ContentPublicController.java
  src/main/java/com/echall/platform/content/domain/dto/ContentResponseDto.java
  src/main/java/com/echall/platform/content/domain/entity/ContentEntity.java
  src/main/java/com/echall/platform/content/domain/enums/ContentStatus.java
  src/main/java/com/echall/platform/content/domain/enums/SearchCondition.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
  src/main/java/com/echall/platform/content/service/ContentService.java
  src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
  src/main/java/com/echall/platform/message/error/code/BookmarkErrorCode.java
  src/main/java/com/echall/platform/message/error/code/ContentErrorCode.java
  src/main/java/com/echall/platform/message/response/BookmarkResponseCode.java
  src/main/java/com/echall/platform/message/status/BookmarkServiceStatus.java
  src/main/java/com/echall/platform/message/status/ContentServiceStatus.java
  src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
  src/main/java/com/echall/platform/user/repository/UserRepository.java
Labels: ✨ FEAT, 🐶 YR, 🔖 LOW, ⚒️ REFACTOR, 🌚 BE

#105 [FEAT] 로그 모니터링 코드 구현
  .gitignore
  src/main/java/com/echall/platform/annotation/LoginLogging.java
  src/main/java/com/echall/platform/aop/LoggingAspect.java
  src/main/java/com/echall/platform/message/status/UserServiceStatus.java
  src/main/java/com/echall/platform/oauth2/OAuth2SuccessHandler.java
  src/main/resources/logback.xml
Labels: ✨ FEAT, 🔖 HIGH, 🌚 BE, 🏀 CW

#108 [SETTING] 도커 컨테이너 logs 매핑
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: 🔖 HIGH, ⚙️ SETTING, 🌚 BE, 🏀 CW

#109 [FEAT] 북마크 기능 추가 및 일부 리팩토링
  src/main/java/com/echall/platform/bookmark/controller/BookmarkApiController.java
  src/main/java/com/echall/platform/bookmark/repository/BookmarkRepository.java
  src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryCustom.java
  src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryImpl.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkService.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/echall/platform/category/controller/CategoryApiController.java
  src/main/java/com/echall/platform/category/controller/CategoryPublicController.java
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/content/controller/ContentApiController.java
  src/main/java/com/echall/platform/content/controller/ContentPublicController.java
  src/main/java/com/echall/platform/content/domain/entity/ContentDocument.java
  src/main/java/com/echall/platform/content/repository/ContentScriptRepository.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
  src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
  src/main/java/com/echall/platform/message/error/code/QuestionErrorCode.java
  src/main/java/com/echall/platform/message/response/ContentResponseCode.java
  src/main/java/com/echall/platform/message/response/QuestionResponseCode.java
  src/main/java/com/echall/platform/message/status/QuestionServiceStatus.java
  src/main/java/com/echall/platform/oauth2/domain/info/OAuth2UserPrincipal.java
  src/main/java/com/echall/platform/question/controller/QuestionApiController.java
  src/main/java/com/echall/platform/question/controller/QuestionPublicController.java
  src/main/java/com/echall/platform/question/domain/dto/QuestionRequestDto.java
  src/main/java/com/echall/platform/question/domain/dto/QuestionResponseDto.java
  src/main/java/com/echall/platform/question/domain/entity/QuestionDocument.java
  src/main/java/com/echall/platform/question/repository/QuestionRepository.java
  src/main/java/com/echall/platform/question/service/QuestionService.java
  src/main/java/com/echall/platform/question/service/QuestionServiceImpl.java
  src/main/java/com/echall/platform/user/controller/UserApiController.java
  src/main/java/com/echall/platform/user/repository/UserRepository.java
  src/main/java/com/echall/platform/util/MongoBaseDocument.java
Labels: ✨ FEAT, 🐶 YR, 🐞 BUGFIX, 🌚 BE

#117 [SETTING] 로그 시간 타임존 설정 및 deploy 수정
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
  src/main/resources/logback.xml
Labels: 🐞 BUGFIX, 🔖 HIGH, ⚙️ SETTING, 🌚 BE, 🏀 CW

#151 [REFACTOR] 리딩/리스닝 컨텐츠 페이지네이션 조회
  src/main/java/com/echall/platform/aop/LoggingAspect.java
  src/main/java/com/echall/platform/category/controller/CategoryApiController.java
  src/main/java/com/echall/platform/category/controller/CategoryPublicController.java
  src/main/java/com/echall/platform/category/domain/entity/CategoryEntity.java
  src/main/java/com/echall/platform/category/repository/CategoryRepository.java
  src/main/java/com/echall/platform/content/controller/ContentPublicController.java
  src/main/java/com/echall/platform/content/domain/dto/ContentResponseDto.java
  src/main/java/com/echall/platform/content/domain/entity/ContentEntity.java
  src/main/java/com/echall/platform/content/repository/ContentRepository.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
  src/main/java/com/echall/platform/content/service/ContentService.java
  src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
  src/main/java/com/echall/platform/crawling/domain/dto/CrawlingResponseDto.java
  src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
  src/main/java/com/echall/platform/message/error/code/CategoryErrorCode.java
  src/main/java/com/echall/platform/message/response/CategoryResponseCode.java
  src/main/java/com/echall/platform/message/status/CategoryServiceStatus.java
  src/main/java/com/echall/platform/util/PaginationDto.java
Labels: ✨ FEAT, 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE

#156 [REFACTORING] 크롤링 이미지 url 수정
  src/main/java/com/echall/platform/content/domain/entity/Script.java
  src/main/java/com/echall/platform/crawling/domain/dto/CrawlingResponseDto.java
  src/main/java/com/echall/platform/crawling/service/CrawlingService.java
  src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
Labels: 🐶 YR, 🔖 LOW, ⚒️ REFACTOR, 🌚 BE

#153 [FEAT] 스크랩 기능 추가 및 북마크에서 스크랩과 유사한 기능 삭제
  src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkRequestDto.java
  src/main/java/com/echall/platform/bookmark/domain/entity/BookmarkEntity.java
  src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryImpl.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/echall/platform/content/controller/ContentPublicController.java
  src/main/java/com/echall/platform/message/ResponseCode.java
  src/main/java/com/echall/platform/message/error/code/BookmarkErrorCode.java
  src/main/java/com/echall/platform/message/error/code/ScrapErrorCode.java
  src/main/java/com/echall/platform/message/response/ScrapResponseCode.java
  src/main/java/com/echall/platform/message/status/BookmarkServiceStatus.java
  src/main/java/com/echall/platform/message/status/ScrapServiceStatus.java
  src/main/java/com/echall/platform/scrap/controller/ScrapApiController.java
  src/main/java/com/echall/platform/scrap/domain/dto/ScrapRequestDto.java
  src/main/java/com/echall/platform/scrap/domain/dto/ScrapResponseDto.java
  src/main/java/com/echall/platform/scrap/domain/entity/ScrapEntity.java
  src/main/java/com/echall/platform/scrap/repository/ScrapRepository.java
  src/main/java/com/echall/platform/scrap/repository/custom/ScrapRepositoryCustom.java
  src/main/java/com/echall/platform/scrap/repository/custom/ScrapRepositoryImpl.java
  src/main/java/com/echall/platform/scrap/service/ScrapService.java
  src/main/java/com/echall/platform/scrap/service/ScrapServiceImpl.java
  src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
Labels: ✨ FEAT, 🐶 YR, 🔖 LOW, ⚒️ REFACTOR, 🌚 BE

#159 [FEAT] 북마크 전체 조회 기능 추가
  src/main/java/com/echall/platform/bookmark/controller/BookmarkApiController.java
  src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkRequestDto.java
  src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkResponseDto.java
  src/main/java/com/echall/platform/bookmark/domain/entity/BookmarkEntity.java
  src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryCustom.java
  src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryImpl.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkService.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/echall/platform/content/repository/ContentRepository.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
  src/main/java/com/echall/platform/message/error/code/BookmarkErrorCode.java
  src/main/java/com/echall/platform/message/status/BookmarkServiceStatus.java
  src/main/java/com/echall/platform/user/repository/UserRepository.java
Labels: ✨ FEAT, 🐶 YR, 🔖 HIGH, 🌚 BE

#161 [REFACTORING] 스크랩 리팩토링 및 조회 기능 추가
  src/main/java/com/echall/platform/message/response/ScrapResponseCode.java
  src/main/java/com/echall/platform/message/status/ScrapServiceStatus.java
  src/main/java/com/echall/platform/scrap/controller/ScrapApiController.java
  src/main/java/com/echall/platform/scrap/domain/dto/ScrapRequestDto.java
  src/main/java/com/echall/platform/scrap/repository/custom/ScrapRepositoryCustom.java
  src/main/java/com/echall/platform/scrap/repository/custom/ScrapRepositoryImpl.java
  src/main/java/com/echall/platform/scrap/service/ScrapService.java
  src/main/java/com/echall/platform/scrap/service/ScrapServiceImpl.java
Labels: 🐶 YR, 🔖 LOW, ⚒️ REFACTOR, 🌚 BE

#163 [HOTFIX] 북마크 디테일 크기 변경
  src/main/java/com/echall/platform/bookmark/domain/entity/BookmarkEntity.java
Labels: 🐶 YR, 🔖 CRITICAL, ⚒️ REFACTOR, 🌚 BE

#167 [HOTFIX] 스크랩 Get 요청 수정
  src/main/java/com/echall/platform/scrap/controller/ScrapApiController.java
  src/main/java/com/echall/platform/scrap/domain/dto/ScrapRequestDto.java
  src/main/java/com/echall/platform/scrap/service/ScrapService.java
  src/main/java/com/echall/platform/scrap/service/ScrapServiceImpl.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#168 [HOTFIX] 스크랩 리턴 타입 수정
  src/main/java/com/echall/platform/content/domain/entity/ContentEntity.java
  src/main/java/com/echall/platform/scrap/domain/dto/ScrapRequestDto.java
  src/main/java/com/echall/platform/scrap/domain/dto/ScrapResponseDto.java
  src/main/java/com/echall/platform/scrap/domain/entity/ScrapEntity.java
  src/main/java/com/echall/platform/scrap/repository/custom/ScrapRepositoryImpl.java
  src/main/java/com/echall/platform/scrap/service/ScrapServiceImpl.java
  src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
Labels: 🐶 YR, 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE

#169 [REFACTORING] 스웨거 리턴 타입 일치
  src/main/java/com/echall/platform/bookmark/controller/BookmarkApiController.java
  src/main/java/com/echall/platform/category/controller/CategoryPublicController.java
  src/main/java/com/echall/platform/content/controller/ContentApiController.java
  src/main/java/com/echall/platform/content/controller/ContentPublicController.java
  src/main/java/com/echall/platform/content/domain/dto/ContentResponseDto.java
  src/main/java/com/echall/platform/question/controller/QuestionApiController.java
  src/main/java/com/echall/platform/question/controller/QuestionPublicController.java
  src/main/java/com/echall/platform/scrap/controller/ScrapApiController.java
  src/main/java/com/echall/platform/scrap/domain/dto/ScrapResponseDto.java
  src/main/java/com/echall/platform/swagger/SwaggerBooleanReturn.java
  src/main/java/com/echall/platform/swagger/SwaggerReturnInterface.java
  src/main/java/com/echall/platform/swagger/SwaggerVoidReturn.java
  src/main/java/com/echall/platform/swagger/bookmark/SwaggerBookmarkCreate.java
  src/main/java/com/echall/platform/swagger/bookmark/SwaggerBookmarkList.java
  src/main/java/com/echall/platform/swagger/bookmark/SwaggerBookmarkMyList.java
  src/main/java/com/echall/platform/swagger/category/SwaggerCategory.java
  src/main/java/com/echall/platform/swagger/content/SwaggerContentCreate.java
  src/main/java/com/echall/platform/swagger/content/SwaggerContentDetail.java
  src/main/java/com/echall/platform/swagger/content/SwaggerContentPreview.java
  src/main/java/com/echall/platform/swagger/content/SwaggerContentUpdate.java
  src/main/java/com/echall/platform/swagger/question/SwaggerQuestionCreate.java
  src/main/java/com/echall/platform/swagger/question/SwaggerQuestionView.java
  src/main/java/com/echall/platform/swagger/scrap/SwaggerScrapCreate.java
  src/main/java/com/echall/platform/swagger/scrap/SwaggerScrapView.java
  src/main/java/com/echall/platform/swagger/user/SwaggerUserMyPage.java
  src/main/java/com/echall/platform/swagger/user/SwaggerUserUpdate.java
  src/main/java/com/echall/platform/user/controller/UserApiController.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 HIGH, 🌚 BE

#170 [REFACTORING] 스크랩 접근 권한 수정
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/scrap/controller/ScrapApiController.java
Labels: 🐶 YR, 🐞 BUGFIX, 🌚 BE

#171 [BUGFIX] 컨텐츠 상세 보기 리스닝 응답에 videoUrl 추가 및 Script 관련 로직 리팩토링
  src/main/java/com/echall/platform/config/MongoConfig.java
  src/main/java/com/echall/platform/config/ScriptConverter.java
  src/main/java/com/echall/platform/content/domain/dto/ContentRequestDto.java
  src/main/java/com/echall/platform/content/domain/dto/ContentResponseDto.java
  src/main/java/com/echall/platform/content/domain/entity/ContentDocument.java
  src/main/java/com/echall/platform/content/domain/entity/ContentEntity.java
  src/main/java/com/echall/platform/content/domain/entity/Script.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
  src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
  src/main/java/com/echall/platform/crawling/domain/dto/CrawlingResponseDto.java
  src/main/java/com/echall/platform/crawling/service/CrawlingService.java
  src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
  src/main/java/com/echall/platform/script/domain/entity/BaseScript.java
  src/main/java/com/echall/platform/script/domain/entity/CNNScript.java
  src/main/java/com/echall/platform/script/domain/entity/ListeningScript.java
  src/main/java/com/echall/platform/script/domain/entity/ReadingScript.java
  src/main/java/com/echall/platform/script/domain/entity/Script.java
  src/main/java/com/echall/platform/script/domain/entity/YoutubeScript.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#172 [REFACTOR] 메인 화면, 프리뷰 화면 아무나 볼 수 있게 권한 설정
  src/main/java/com/echall/platform/config/SecurityConfig.java
Labels: 🔖 LOW, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#176 [REFACTORING] 문제, 유저 리팩토링
  src/main/java/com/echall/platform/content/domain/entity/ContentEntity.java
  src/main/java/com/echall/platform/question/domain/dto/QuestionResponseDto.java
  src/main/java/com/echall/platform/question/domain/entity/QuestionDocument.java
  src/main/java/com/echall/platform/question/domain/enums/QuestionType.java
  src/main/java/com/echall/platform/question/service/QuestionServiceImpl.java
  src/main/java/com/echall/platform/script/domain/entity/CNNScript.java
  src/main/java/com/echall/platform/script/domain/entity/Script.java
  src/main/java/com/echall/platform/script/domain/entity/YoutubeScript.java
  src/main/java/com/echall/platform/swagger/user/SwaggerUserMyTime.java
  src/main/java/com/echall/platform/user/controller/UserApiController.java
  src/main/java/com/echall/platform/user/domain/dto/UserResponseDto.java
  src/main/java/com/echall/platform/user/service/UserService.java
  src/main/java/com/echall/platform/util/RandomNicknameGenerator.java
Labels: 🐶 YR, 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE

#177 [SETTING] 배포 서버에도 로그 한국 시간으로 찍히게 시도
  src/main/java/com/echall/platform/EnglishChallengePlatformApplication.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
Labels: 🔖 MEDIUM, ⚙️ SETTING, 🌚 BE, 🏀 CW

#182 [FEAT] 스크랩 많이 한 컨텐츠 리턴 기능
  src/main/java/com/echall/platform/bookmark/controller/BookmarkApiController.java
  src/main/java/com/echall/platform/content/controller/ContentPublicController.java
  src/main/java/com/echall/platform/content/domain/dto/ContentResponseDto.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
  src/main/java/com/echall/platform/content/service/ContentService.java
  src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
  src/main/java/com/echall/platform/message/ApiCustomResponse.java
  src/main/java/com/echall/platform/message/ResponseEntityFactory.java
  src/main/java/com/echall/platform/message/error/GlobalExceptionHandler.java
  src/main/java/com/echall/platform/scrap/controller/ScrapApiController.java
  src/main/java/com/echall/platform/scrap/repository/ScrapRepository.java
  src/main/java/com/echall/platform/swagger/content/SwaggerContentByScrapCount.java
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#184 [FEAT] 로그아웃 기능 개발
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/message/response/UserResponseCode.java
  src/main/java/com/echall/platform/message/status/UserServiceStatus.java
  src/main/java/com/echall/platform/oauth2/repository/RefreshTokenRepository.java
  src/main/java/com/echall/platform/user/controller/UserApiController.java
  src/main/java/com/echall/platform/user/controller/UserPublicController.java
  src/main/java/com/echall/platform/user/service/UserService.java
  src/main/java/com/echall/platform/util/CookieUtil.java
Labels: ✨ FEAT, 🔖 LOW, 🌚 BE, 🏀 CW

#188 [FEAT] 로그인 상태 확인 API 추가
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/message/response/UserResponseCode.java
  src/main/java/com/echall/platform/message/status/UserServiceStatus.java
  src/main/java/com/echall/platform/user/controller/UserApiController.java
  src/main/java/com/echall/platform/user/service/UserService.java
  src/main/java/com/echall/platform/util/CookieUtil.java
Labels: ✨ FEAT, 🐶 YR, 🔖 CRITICAL, 🌚 BE

#187 [REFACTOR] 컨텐츠 디테일 화면 아무나 볼 수 있게 권한 수정
  src/main/java/com/echall/platform/config/SecurityConfig.java
Labels: 🔖 LOW, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#189 [DOCS] 리드미 1차 작성
  README.md
Labels: 📑 DOCS, 🔖 LOW, 🏀 CW

#191 [HOTFIX] 프론트 요청에 따른 스크랩 정렬 조건 추가
  src/main/java/com/echall/platform/scrap/repository/custom/ScrapRepositoryImpl.java
Labels: ✨ FEAT, 🐶 YR, 🔖 CRITICAL, 🌚 BE

#195 [HOTFIX] JSON 특수문자 처리
  src/main/java/com/echall/platform/crawling/service/TranslateService.java
Labels: 🐶 YR, 🔖 CRITICAL, 🌚 BE, 🐞 BUG

#193 [FEAT] 검색 기능 추가
  src/main/java/com/echall/platform/content/controller/ContentPublicController.java
  src/main/java/com/echall/platform/content/domain/dto/ContentRequestDto.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
  src/main/java/com/echall/platform/content/service/ContentService.java
  src/main/java/com/echall/platform/content/service/ContentServiceImpl.java
  src/main/java/com/echall/platform/message/error/code/ContentErrorCode.java
  src/main/java/com/echall/platform/message/status/ContentServiceStatus.java
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#201 [REFACTORING] 북마크 조회 조건 및 리턴 타입 추가
  src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkResponseDto.java
  src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryImpl.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryCustom.java
  src/main/java/com/echall/platform/content/repository/custom/ContentRepositoryImpl.java
Labels: 🐶 YR, 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE

#203 [HOTFIX] 랜덤으로 닉네임 생성되게 수정
  src/main/java/com/echall/platform/util/RandomNicknameGenerator.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 MEDIUM, 🌚 BE

#206 [HOTFIX] 프론트 요청에 따른 북마크 상세조회 조건 수정
  src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
Labels: 🐶 YR, 🐞 BUGFIX, 🌚 BE

#213 [FEAT] 유튜브 북마크 시 시작 시간 리턴
  src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkRequestDto.java
  src/main/java/com/echall/platform/bookmark/domain/dto/BookmarkResponseDto.java
  src/main/java/com/echall/platform/bookmark/domain/entity/BookmarkEntity.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/echall/platform/user/service/UserService.java
  src/main/java/com/echall/platform/util/CookieUtil.java
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#216 [REFACTOR] OAUTH2 로그인 리다이렉트 URL 동적으로 추가하는 로직 개발
  src/main/java/com/echall/platform/config/SecurityConfig.java
  src/main/java/com/echall/platform/oauth2/OAuth2SuccessHandler.java
  src/main/java/com/echall/platform/oauth2/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/echall/platform/util/CookieUtil.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#223 [HOTFIX] 북마크 중복 생성 체크 잘못된 메소드명 수정
  src/main/java/com/echall/platform/bookmark/repository/BookmarkRepository.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 HIGH, 🌚 BE

#225 [HOTFIX] 유저 초기 정보 입력시 ACTIVATE 로 바뀌지 않는 로직 수정
  src/main/java/com/echall/platform/user/domain/entity/UserEntity.java
  src/main/java/com/echall/platform/user/service/UserService.java
Labels: 🐞 BUGFIX, 🌚 BE

#222 [BUGFIX] 소셜로그인 실패 로그 레벨 변경 및 OAuth2AuthenticationException 이외 예외 로그 추가
  src/main/java/com/echall/platform/oauth2/OAuth2FailureHandler.java
Labels: 🐞 BUGFIX, 🔖 HIGH, 🌚 BE, 🏀 CW

#229 [HOTFIX] json 타입 에러로 번역 실패일 때 "" 로 채우고 로그 남기는 방식으로 수정
  src/main/java/com/echall/platform/crawling/service/TranslateService.java
Labels: 🐶 YR, 🌚 BE, 🐞 BUG

#236 [BUGFIX] 남이 생성한 북마크에 영향 받지 않도록 수정
  src/main/java/com/echall/platform/bookmark/repository/BookmarkRepository.java
  src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryCustom.java
  src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryImpl.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#237 DEV to MAIN
  README.md
  src/main/java/com/echall/platform/bookmark/repository/BookmarkRepository.java
  src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryCustom.java
  src/main/java/com/echall/platform/bookmark/repository/custom/BookmarkRepositoryImpl.java
  src/main/java/com/echall/platform/bookmark/service/BookmarkServiceImpl.java
  src/main/java/com/echall/platform/crawling/service/TranslateService.java
Labels: 🪨 DEPLOY, 🌚 BE, 🏀 CW

#238 [BUGFIX] OAuth2 인증 과정에서 필요한 쿠키 유효 시간 10초에서 3분으로 확장
  src/main/java/com/echall/platform/oauth2/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/echall/platform/util/CookieUtil.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#240 Update README.md
  README.md
Labels: 📑 DOCS, 🌚 BE

#242 [HOTFIX] 번역 API exception 받을 수 있게 catch 위치 수정
  src/main/java/com/echall/platform/crawling/service/CrawlingServiceImpl.java
Labels: 🐶 YR, 🌚 BE

#250 [SETTING] Docker logs 매핑 삭제
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: 🔖 HIGH, ⚙️ SETTING, 🌚 BE, 🏀 CW

#251 [SETTING] 도커 -v 옵션 다시 추가
  .github/workflows/dev-deploy.yml
  .github/workflows/prod-deploy.yml
Labels: 🔖 HIGH, ⚙️ SETTING, 🌚 BE, 🏀 CW

#253 [BUGFIX] 애플리케이션 타임존 설정 추가
  user-api/src/main/java/com/biengual/userapi/UserApiApplication.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#268 [REFACTORING] 삭제된 실패 메세지에 따라 BOOKMARK_ALREADY_EXISTS code 수정
  user-api/src/main/java/com/biengual/userapi/message/status/BookmarkServiceStatus.java
Labels: 🐶 YR, 📑 DOCS, ⚒️ REFACTOR

#270 [REFACTOR] 모든 `@PatchMapping`을 `@PutMapping`으로 수정
  user-api/src/main/java/com/biengual/userapi/content/controller/ContentApiController.java
  user-api/src/main/java/com/biengual/userapi/user/controller/UserApiController.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#272 [REFACTOR] 컨트롤러 응답 리턴 객체 간결화
  user-api/build.gradle
  user-api/src/main/java/com/biengual/userapi/aop/LoggingAspect.java
  user-api/src/main/java/com/biengual/userapi/bookmark/controller/BookmarkApiController.java
  user-api/src/main/java/com/biengual/userapi/bookmark/repository/custom/BookmarkRepositoryImpl.java
  user-api/src/main/java/com/biengual/userapi/category/controller/CategoryPublicController.java
  user-api/src/main/java/com/biengual/userapi/content/controller/ContentApiController.java
  user-api/src/main/java/com/biengual/userapi/content/controller/ContentPublicController.java
  user-api/src/main/java/com/biengual/userapi/message/ApiCustomResponse.java
  user-api/src/main/java/com/biengual/userapi/message/ResponseEntityFactory.java
  user-api/src/main/java/com/biengual/userapi/message/error/GlobalExceptionHandler.java
  user-api/src/main/java/com/biengual/userapi/question/controller/QuestionApiController.java
  user-api/src/main/java/com/biengual/userapi/question/controller/QuestionPublicController.java
  user-api/src/main/java/com/biengual/userapi/scrap/controller/ScrapApiController.java
  user-api/src/main/java/com/biengual/userapi/test/TestController.java
  user-api/src/main/java/com/biengual/userapi/user/controller/UserApiController.java
  user-api/src/test/java/com/biengual/userapi/controller/UserApiControllerTest.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#275 [REFACTOR] 프론트 요청 : wordIndex 삭제
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkCommand.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkEntity.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkInfo.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkRepositoryImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkRequestDto.java
  user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkResponseDto.java
Labels: 🐶 YR, 🔖 LOW, ⚒️ REFACTOR, 🌚 BE

#278 [REFACTOR] Scrap Layered Architecture 형태로 수정
  user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkApiController.java
  user-api/src/main/java/com/biengual/userapi/content/repository/custom/ContentRepositoryImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/application/ScrapFacade.java
  user-api/src/main/java/com/biengual/userapi/scrap/application/ScrapServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/controller/ScrapApiController.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapCommand.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapEntity.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapInfo.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapReader.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapRepository.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapRepositoryCustom.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapRepositoryImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapService.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapStore.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/dto/ScrapRequestDto.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/dto/ScrapResponseDto.java
  user-api/src/main/java/com/biengual/userapi/scrap/infrastructure/ScrapReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/infrastructure/ScrapStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapApiController.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapResponseDto.java
  user-api/src/main/java/com/biengual/userapi/scrap/service/ScrapService.java
  user-api/src/main/java/com/biengual/userapi/scrap/service/ScrapServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/swagger/scrap/SwaggerScrapCreate.java
  user-api/src/main/java/com/biengual/userapi/swagger/scrap/SwaggerScrapView.java
  user-api/src/main/java/com/biengual/userapi/user/domain/entity/UserEntity.java
Labels: 🐶 YR, 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE

#281 [FEAT] flyway 추가 및 V1__init.sql 초기 DB 세팅
  user-api/build.gradle
  user-api/src/main/resources/application.yml
  user-api/src/main/resources/db/migration/V1.0.1__init.sql
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#279 [REFACTOR] 본인 정보 수정 기능 리팩토링 + @
  user-api/build.gradle
  user-api/src/main/java/com/biengual/userapi/annotation/DataProvider.java
  user-api/src/main/java/com/biengual/userapi/annotation/Facade.java
  user-api/src/main/java/com/biengual/userapi/annotation/LoginLogging.java
  user-api/src/main/java/com/biengual/userapi/aop/LoggingAspect.java
  user-api/src/main/java/com/biengual/userapi/bookmark/application/BookmarkServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkEntity.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkReader.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkRepositoryImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/service/BookmarkServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/common/config/QueryDslConfig.java
  user-api/src/main/java/com/biengual/userapi/common/constant/BadRequestMessageConstant.java
  user-api/src/main/java/com/biengual/userapi/common/constant/RestrictionConstant.java
  user-api/src/main/java/com/biengual/userapi/common/entity/BaseEntity.java
  user-api/src/main/java/com/biengual/userapi/content/domain/entity/ContentEntity.java
  user-api/src/main/java/com/biengual/userapi/message/error/GlobalExceptionHandler.java
  user-api/src/main/java/com/biengual/userapi/message/error/code/RequestErrorCode.java
  user-api/src/main/java/com/biengual/userapi/message/response/UserResponseCode.java
  user-api/src/main/java/com/biengual/userapi/message/status/RequestServiceStatus.java
  user-api/src/main/java/com/biengual/userapi/oauth2/OAuth2SuccessHandler.java
  user-api/src/main/java/com/biengual/userapi/oauth2/TokenProvider.java
  user-api/src/main/java/com/biengual/userapi/oauth2/domain/info/OAuth2UserPrincipal.java
  user-api/src/main/java/com/biengual/userapi/oauth2/service/RefreshTokenService.java
  user-api/src/main/java/com/biengual/userapi/oauth2/service/TokenService.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapEntity.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapRepositoryImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/infrastructure/ScrapStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/service/ScrapServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/swagger/user/SwaggerUserMyPage.java
  user-api/src/main/java/com/biengual/userapi/swagger/user/SwaggerUserMyTime.java
  user-api/src/main/java/com/biengual/userapi/swagger/user/SwaggerUserUpdate.java
  user-api/src/main/java/com/biengual/userapi/user/application/UserFacade.java
  user-api/src/main/java/com/biengual/userapi/user/application/UserServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserCategoryEntity.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserCommand.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserEntity.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserReader.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserService.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserStore.java
  user-api/src/main/java/com/biengual/userapi/user/domain/dto/UserRequestDto.java
  user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/user/presentation/UserApiController.java
  user-api/src/main/java/com/biengual/userapi/user/presentation/UserDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/user/presentation/UserPublicController.java
  user-api/src/main/java/com/biengual/userapi/user/presentation/UserRequestDto.java
  user-api/src/main/java/com/biengual/userapi/user/presentation/UserResponseDto.java
  user-api/src/main/java/com/biengual/userapi/user/repository/UserCategoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/user/repository/UserCategoryRepository.java
  user-api/src/main/java/com/biengual/userapi/user/repository/UserRepository.java
  user-api/src/main/resources/db/migration/V1.1.0__create.sql
  user-api/src/test/java/com/biengual/userapi/service/UserServiceTest.java
Labels: 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#284 [REFACTOR] 첫로그인 시 리다이렉트 URL 변경
  user-api/src/main/java/com/biengual/userapi/oauth2/OAuth2SuccessHandler.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserEntity.java
  user-api/src/main/java/com/biengual/userapi/util/CookieUtil.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#286 [REFACTOR] User 도메인 리팩토링
  user-api/src/main/java/com/biengual/userapi/oauth2/OAuth2SuccessHandler.java
  user-api/src/main/java/com/biengual/userapi/oauth2/controller/TokenApiController.java
  user-api/src/main/java/com/biengual/userapi/oauth2/service/RefreshTokenService.java
  user-api/src/main/java/com/biengual/userapi/oauth2/service/TokenService.java
  user-api/src/main/java/com/biengual/userapi/swagger/user/SwaggerUserMyPage.java
  user-api/src/main/java/com/biengual/userapi/swagger/user/SwaggerUserMyTime.java
  user-api/src/main/java/com/biengual/userapi/swagger/user/SwaggerUserUpdate.java
  user-api/src/main/java/com/biengual/userapi/user/application/UserFacade.java
  user-api/src/main/java/com/biengual/userapi/user/application/UserServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/user/domain/RefreshTokenStore.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserInfo.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserReader.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserService.java
  user-api/src/main/java/com/biengual/userapi/user/infrastructure/RefreshTokenStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/user/presentation/UserDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/user/presentation/UserPublicController.java
  user-api/src/main/java/com/biengual/userapi/user/presentation/UserResponseDto.java
  user-api/src/main/java/com/biengual/userapi/user/repository/UserCategoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/user/repository/UserCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/user/repository/UserRepository.java
  user-api/src/main/java/com/biengual/userapi/util/CookieUtil.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#287 [REFACTOR] JPQL -> JPAQueryFactory 로 queryDsl 리팩토링
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkCommand.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkEntity.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkRepository.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkRepositoryCustom.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkRepositoryImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapEntity.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapRepository.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapRepositoryCustom.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapRepositoryImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/infrastructure/ScrapReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/infrastructure/ScrapStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserEntity.java
Labels: 🐶 YR, 🔖 LOW, ⚒️ REFACTOR, 🌚 BE

#291 [REFACTOR] Categroy 도메인 Layered Architecture 리팩토링
  user-api/src/main/java/com/biengual/userapi/category/application/CategoryFacade.java
  user-api/src/main/java/com/biengual/userapi/category/application/CategoryServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/category/domain/CategoryEntity.java
  user-api/src/main/java/com/biengual/userapi/category/domain/CategoryInfo.java
  user-api/src/main/java/com/biengual/userapi/category/domain/CategoryReader.java
  user-api/src/main/java/com/biengual/userapi/category/domain/CategoryService.java
  user-api/src/main/java/com/biengual/userapi/category/domain/dto/CategoryRequestDto.java
  user-api/src/main/java/com/biengual/userapi/category/domain/dto/CategoryResponseDto.java
  user-api/src/main/java/com/biengual/userapi/category/infrastructure/CategoryReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/category/presentation/CategoryDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/category/presentation/CategoryPublicController.java
  user-api/src/main/java/com/biengual/userapi/category/presentation/CategoryResponseDto.java
  user-api/src/main/java/com/biengual/userapi/category/repository/CategoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/category/repository/CategoryRepository.java
  user-api/src/main/java/com/biengual/userapi/category/service/CategoryService.java
  user-api/src/main/java/com/biengual/userapi/category/service/CategoryServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/entity/ContentEntity.java
  user-api/src/main/java/com/biengual/userapi/content/service/ContentServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/crawling/domain/dto/CrawlingResponseDto.java
  user-api/src/main/java/com/biengual/userapi/swagger/category/SwaggerCategory.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserCategoryEntity.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserCommand.java
  user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserStoreImpl.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#294 [REFACTOR] content-api querydsl 수정 및 일부 api 수정
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentFacade.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCommand.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentDocument.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentEntity.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentRepositoryCustom.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentRepositoryImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentService.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentStore.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentApiController.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentRequestDto.java
  user-api/src/main/java/com/biengual/userapi/content/service/ContentServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/message/response/ContentResponseCode.java
  user-api/src/main/java/com/biengual/userapi/scrap/service/ScrapServiceImpl.java
Labels: 🐶 YR, 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE

#296 [REFACTOR] 컨텐츠 Public API 리팩토링
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkInfo.java
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkResponseDto.java
  user-api/src/main/java/com/biengual/userapi/category/repository/CategoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/common/constant/BadRequestMessageConstant.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentFacade.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCommand.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentDocumentReader.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentDocumentRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentEntity.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentReader.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentRepositoryCustom.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentRepositoryImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentService.java
  user-api/src/main/java/com/biengual/userapi/content/domain/SearchCondition.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentDocumentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentApiController.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentRequestDto.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
  user-api/src/main/java/com/biengual/userapi/content/repository/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/message/error/GlobalExceptionHandler.java
  user-api/src/main/java/com/biengual/userapi/message/error/code/ContentErrorCode.java
  user-api/src/main/java/com/biengual/userapi/message/error/code/RequestErrorCode.java
  user-api/src/main/java/com/biengual/userapi/message/error/code/ServerError.java
  user-api/src/main/java/com/biengual/userapi/message/status/ContentServiceStatus.java
  user-api/src/main/java/com/biengual/userapi/message/status/ServerServiceStatus.java
  user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/swagger/content/SwaggerContentListeningPreview.java
  user-api/src/main/java/com/biengual/userapi/swagger/content/SwaggerContentListeningView.java
  user-api/src/main/java/com/biengual/userapi/swagger/content/SwaggerContentReadingPreview.java
  user-api/src/main/java/com/biengual/userapi/swagger/content/SwaggerContentReadingView.java
  user-api/src/main/java/com/biengual/userapi/swagger/content/SwaggerContentScrapPreview.java
  user-api/src/main/java/com/biengual/userapi/swagger/content/SwaggerContentSearchPreview.java
  user-api/src/main/java/com/biengual/userapi/util/PaginationDto.java
  user-api/src/main/java/com/biengual/userapi/util/PaginationInfo.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#298 [BUGFIX] 썸네일 URL에 컨텐츠 URL로 들어가고 있던 것을 올바르게 수정
  user-api/src/main/java/com/biengual/userapi/content/repository/ContentCustomRepository.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#300 [REFACTOR] Admin 페이지 컨텐츠 상태 무관하게 조회
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentFacade.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentEntity.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentReader.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentService.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentApiController.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
  user-api/src/main/java/com/biengual/userapi/content/repository/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/swagger/content/SwaggerContentAdminView.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserCategoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserCategoryRepository.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserRepository.java
  user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserStoreImpl.java
  user-api/src/main/resources/db/migration/V1.2.0__alter.sql
  user-api/src/test/java/com/biengual/userapi/service/UserServiceTest.java
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#301 [REFACTOR] 페이지 넘버 1부터 시작하게끔 수정
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentApiController.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
Labels: 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#303 [FEAT] question 생성 시 num_of_quiz 업데이트 로직 추가
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentEntity.java
  user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionStoreImpl.java
Labels: ✨ FEAT, 🐶 YR, 🔖 CRITICAL, 🌚 BE, 🐞 BUG

#305 [HOTFIX] 미반영 pr 오류
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 HIGH, 🌚 BE

#311 [REFACTOR] 프론트 요청에 따른 컨텐츠 디테일 조회 리팩토링
  user-api/src/main/java/com/biengual/userapi/content/application/ContentFacade.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCommand.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentDocumentReader.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentReader.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentService.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentStore.java
  user-api/src/main/java/com/biengual/userapi/content/domain/UserContentBookmarks.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentDocumentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
Labels: 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#314 [BUGFIX] 유저의 전체 컨텐츠에 대한 북마크를 찾고 있던 것을 해당 컨텐츠의 유저 북마크로 수정
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkRepository.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#315 [REFACTOR] 프론트 요청에 따른 나의 스크랩 조회, 나의 북마크 전체 조회 리팩토링
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkInfo.java
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkApiController.java
  user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkResponseDto.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapInfo.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapResponseDto.java
Labels: 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#317 [BUGFIX] robots.txt 추가
  user-api/src/main/resources/static/robots.txt
Labels: 🐞 BUGFIX, 🔖 LOW, 🌚 BE, 🏀 CW

#318 [BUGFIX] robots.txt 다 허용 못하게 설정
  user-api/src/main/resources/static/robots.txt
Labels: 🐞 BUGFIX, 🔖 LOW, 🌚 BE, 🏀 CW

#321 [BUGFIX] 컨텐츠 디테일 조회시 bookmarkId도 추가로 보내도록 수정
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/domain/UserContentBookmarks.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#323 [REFACTOR] 컨텐츠 미리 보기에 isScrapped 추가
  user-api/src/main/java/com/biengual/userapi/content/application/ContentFacade.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCommand.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentReader.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentService.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentApiController.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
  user-api/src/main/java/com/biengual/userapi/scrap/infrastructure/ScrapReaderImpl.java
Labels: 🐶 YR, ⚒️ REFACTOR, 🌚 BE
