Repository Kernel360/F2-BIENGUAL-BE, pull requests merged in 2024-11, with the labels that each got.

#324 [FEAT] 카테고리 분류기 추가 및 적용
  .github/workflows/dev-deploy.yml
  .gitignore
  biengual-core/src/main/java/com/biengual/core/constant/ServiceConstant.java
  user-api/build.gradle
  user-api/src/main/java/com/biengual/userapi/config/StanfordCoreNLPConfig.java
  user-api/src/main/java/com/biengual/userapi/config/Word2VecConfig.java
  user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/nlp/CategoryClassifier.java
  user-api/src/main/java/com/biengual/userapi/nlp/CategoryCustomDictionary.java
  user-api/src/main/java/com/biengual/userapi/nlp/NLPAnalyzer.java
  user-api/src/main/resources/yml/application-dev.yml
  user-api/src/main/resources/yml/application-local.yml
  user-api/src/main/resources/yml/application-prod.yml
Labels: ✨ FEAT, 🔖 HIGH, 🌚 BE, 🏀 CW

#325 [FIX] bootJar 설정 추가
  user-api/build.gradle
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#326 [Feat] Word2Vec 모델 경량화 1차
  .github/workflows/dev-deploy.yml
Labels: ✨ FEAT, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#327 [FEAT] Word2Vec 모델 경량화 2차
  .gitignore
  user-api/src/main/java/com/biengual/userapi/nlp/NLPAnalyzer.java
Labels: ✨ FEAT, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#329 [SETTING] NLP 사용을 위한 운영 서버 작업
  .github/workflows/prod-deploy.yml
Labels: 🔖 LOW, ⚙️ SETTING, 🌚 BE, 🏀 CW

#332 [REFACTOR] 컨텐츠 디테일 조회 시 응답에 isScrapped 추가
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapApiController.java
Labels: 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#333 [FEAT] 스프링 배치 및 포인트 기능 일부 추가
  biengual-core/src/main/java/com/biengual/core/constant/BadRequestMessageConstant.java
  biengual-core/src/main/java/com/biengual/core/constant/RestrictionConstant.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/pointdatamart/PointDataMart.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/pointhistory/PointHistoryEntity.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/user/UserEntity.java
  biengual-core/src/main/java/com/biengual/core/enums/PointReason.java
  biengual-core/src/main/java/com/biengual/core/response/error/code/PointErrorCode.java
  biengual-core/src/main/java/com/biengual/core/response/error/code/PointHistoryErrorCode.java
  biengual-core/src/main/java/com/biengual/core/response/status/PointHistoryServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/status/PointServiceStatus.java
  user-api/build.gradle
  user-api/src/main/java/com/biengual/userapi/batch/BatchScheduler.java
  user-api/src/main/java/com/biengual/userapi/config/MongoConfig.java
  user-api/src/main/java/com/biengual/userapi/config/PointDataMartJobConfig.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentFacade.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentReader.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentService.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentStore.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
  user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/mission/domain/MissionReader.java
  user-api/src/main/java/com/biengual/userapi/mission/domain/MissionStore.java
  user-api/src/main/java/com/biengual/userapi/mission/infrastructure/MissionReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/mission/infrastructure/MissionStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/oauth2/handler/OAuth2SuccessHandler.java
  user-api/src/main/java/com/biengual/userapi/pointdatamart/domain/PointDataMartRepository.java
  user-api/src/main/java/com/biengual/userapi/pointhistory/domain/PointHistoryRepository.java
  user-api/src/main/java/com/biengual/userapi/pointhistory/domain/PointHistoryStore.java
  user-api/src/main/java/com/biengual/userapi/pointhistory/infrastructure/PointHistoryStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapApiController.java
  user-api/src/main/java/com/biengual/userapi/user/application/UserFacade.java
  user-api/src/main/java/com/biengual/userapi/user/application/UserServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserReader.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserService.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserStore.java
  user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserStoreImpl.java
  user-api/src/main/resources/application.yml
  user-api/src/main/resources/db/migration/V1.4.0__create.sql
  user-api/src/main/resources/db/migration/V1.4.1__create.sql
  user-api/src/main/resources/db/migration/V1.4.2__alter.sql
  user-api/src/main/resources/yml/logging/application-log.yml
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#337 [FEAT] 학습률 업데이트 API 기능 개발
  biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentEntity.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/userlearninghistory/UserLearningHistoryEntity.java
  biengual-core/src/main/java/com/biengual/core/response/status/LearningServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/success/LearningSuccessCode.java
  user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java
  user-api/src/main/java/com/biengual/userapi/learning/application/LearningServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningCommand.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningService.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningStore.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/UserLearningHistoryRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/learning/presentation/LearningDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/learning/presentation/LearningPublicController.java
  user-api/src/main/java/com/biengual/userapi/learning/presentation/dto/UpdateLearningRateDto.java
  user-api/src/main/resources/db/migration/V1.5.0__create.sql
Labels: ✨ FEAT, 🔖 HIGH, 🌚 BE, 🏀 CW

#339 [REFACTOR] oauth2 인증 유효시간 3 -> 5분으로 변경
  biengual-core/src/main/java/com/biengual/core/util/CookieUtil.java
Labels: 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#341 [REFACTOR] 컨텐츠 디테일 조회에 learningRate 추가
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/UserLearningHistoryCustomRepository.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#342 [FEAT] 포인트 사용 내역 저장 기능 추가
  biengual-core/src/main/java/com/biengual/core/annotation/Manager.java
  biengual-core/src/main/java/com/biengual/core/annotation/Validator.java
  biengual-core/src/main/java/com/biengual/core/constant/RestrictionConstant.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/pointdatamart/PointDataMart.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/usercontenthistory/PaymentContentHistoryEntity.java
  biengual-core/src/main/java/com/biengual/core/enums/PointReason.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentFacade.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
  user-api/src/main/java/com/biengual/userapi/mission/application/MissionServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/payment/domain/PaymentReader.java
  user-api/src/main/java/com/biengual/userapi/payment/domain/PaymentRepository.java
  user-api/src/main/java/com/biengual/userapi/payment/domain/PaymentStore.java
  user-api/src/main/java/com/biengual/userapi/payment/infrastructure/PaymentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/payment/infrastructure/PaymentStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/point/domain/PointManager.java
  user-api/src/main/java/com/biengual/userapi/schedule/application/ScheduleServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/user/application/UserFacade.java
  user-api/src/main/java/com/biengual/userapi/user/application/UserServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/user/domain/UserService.java
  user-api/src/main/java/com/biengual/userapi/validator/PointValidator.java
  user-api/src/main/resources/db/migration/V1.6.0__alter.sql
  user-api/src/main/resources/db/migration/V1.7.0__create.sql
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#344 [FEAT] 컨텐츠 preview, search, scrap-count 에 isPointRequired 추가
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#345 [SETTING] Redis Lettuce 세팅
  biengual-core/src/main/java/com/biengual/core/domain/redis/RedisDto.java
  user-api/src/main/java/com/biengual/userapi/config/RedisConfig.java
Labels: 🔖 LOW, ⚙️ SETTING, 🌚 BE, 🏀 CW

#346 [FEAT] 유저 최근 학습 컨텐츠 조회 기능 개발
  biengual-core/src/main/java/com/biengual/core/domain/redis/RedisDto.java
  user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java
  user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardReader.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardService.java
  user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/GetRecentLearningDto.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/UserLearningHistoryCustomRepository.java
Labels: ✨ FEAT, 🔖 MEDIUM, 🌚 BE, 🏀 CW

#349 [FIX] 잘못된 Swagger Example Value 수정
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetRecentLearningDto.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/swagger/SwaggerGetRecentLearning.java
  user-api/src/main/java/com/biengual/userapi/learning/presentation/LearningPublicController.java
  user-api/src/main/java/com/biengual/userapi/learning/presentation/swagger/SwaggerUpdateLearningRate.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#351 [FEAT] 최근 미션 기록 조회 기능 추가
  biengual-core/src/main/java/com/biengual/core/response/status/MissionHistoryServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/success/MissionHistorySuccessCode.java
  user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/application/MissionHistoryServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/domain/MissionHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/domain/MissionHistoryInfo.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/domain/MissionHistoryReader.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/domain/MissionHistoryService.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/infrastructure/MissionHistoryReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/presentation/MissionHistoryDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/presentation/MissionHistoryPublicController.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/presentation/RecentHistoryDto.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/presentation/swagger/SwaggerMissionHistoryRecent.java
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#352 [HOTFIX] 5일 -> 7일 수정 및 컨텐츠 조회 시 컨텐츠 생성 날짜 확인하는 로직 빠진 부분 추가
  biengual-core/src/main/java/com/biengual/core/constant/RestrictionConstant.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/presentation/MissionHistoryPublicController.java
Labels: 🐶 YR, 🔖 CRITICAL, 🌚 BE, 🐞 BUG

#354 [HOTFIX] 미션 포인트 중복 업데이트 로직 해결
  user-api/src/main/java/com/biengual/userapi/mission/application/MissionServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/validator/PointValidator.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 HIGH, 🌚 BE

#358 [REFACTOR] 컨텐츠를 보여주는 API 들의 응답에 영상 길이를 포함하여 보내도록 수정
  biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentEntity.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCommand.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
  user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetRecentLearningDto.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/UserLearningHistoryCustomRepository.java
  user-api/src/main/resources/db/migration/V1.8.0__alter.sql
Labels: 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#362 [HOTFIX] 기존 문제 삭제용 API 삭제
  biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentEntity.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentDocumentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/question/application/QuestionServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/question/domain/QuestionStore.java
  user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/question/presentation/QuestionApiController.java
Labels: ✨ FEAT, 🐶 YR, 🔖 LOW, 🌚 BE

#363 [FEAT] 학습 관련 내역을 위한 기능 개발
  biengual-core/src/main/java/com/biengual/core/domain/entity/learning/CategoryLearningHistoryEntity.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/learning/LearningHistoryEntity.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/learning/RecentLearningHistoryEntity.java
  biengual-core/src/main/java/com/biengual/core/util/PeriodUtil.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentReader.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
  user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetRecentLearningDto.java
  user-api/src/main/java/com/biengual/userapi/learning/application/LearningServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/CategoryLearningHistoryRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningCommand.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningHistoryRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningService.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningStore.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/RecentLearningHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/RecentLearningHistoryRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/UserLearningHistoryRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/learning/presentation/LearningDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/learning/presentation/LearningPublicController.java
  user-api/src/main/java/com/biengual/userapi/learning/presentation/dto/RecordLearningRateDto.java
  user-api/src/main/java/com/biengual/userapi/learning/presentation/swagger/SwaggerRecordLearningRate.java
  user-api/src/main/resources/db/migration/V1.10.0__create.sql
  user-api/src/main/resources/db/migration/V1.10.1__create.sql
  user-api/src/main/resources/db/migration/V1.10.2__alter.sql
  user-api/src/main/resources/db/migration/V1.10.3__alter.sql
  user-api/src/main/resources/db/migration/V1.10.4__update.sql
  user-api/src/main/resources/db/migration/V1.10.5__alter.sql
Labels: ✨ FEAT, 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#364 [Feat] 월별 카테고리별 학습량 조회 기능 개발
  biengual-core/src/main/java/com/biengual/core/constant/BadRequestMessageConstant.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/learning/RecentLearningHistoryEntity.java
  biengual-core/src/main/java/com/biengual/core/response/status/DashboardServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/success/DashboardSuccessCode.java
  biengual-core/src/main/java/com/biengual/core/util/PeriodUtil.java
  user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardReader.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardService.java
  user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetCategoryLearningDto.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetRecentLearningDto.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/swagger/SwaggerGetCategoryLearning.java
  user-api/src/main/java/com/biengual/userapi/learning/application/LearningServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/CategoryLearningHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/RecentLearningHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/validator/LearningValidator.java
Labels: ✨ FEAT, 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#356 [TEST] 조회수 동시성 테스트
  biengual-core/build.gradle
  biengual-core/src/testFixtures/java/com/biengual/core/domain/entity/content/ContentDomainFixture.java
  biengual-core/src/testFixtures/java/com/biengual/core/domain/entity/content/ContentEntityWithVersion.java
  user-api/build.gradle
  user-api/src/test/java/com/biengual/userapi/concurrency/SimpleConcurrencyTest.java
  user-api/src/test/java/com/biengual/userapi/config/TestJpaConfig.java
  user-api/src/test/java/com/biengual/userapi/config/TestQueryDslConfig.java
  user-api/src/test/java/com/biengual/userapi/config/TestRedisRedissonConfig.java
  user-api/src/test/java/com/biengual/userapi/repository/OptimisticLockContentRepository.java
  user-api/src/test/java/com/biengual/userapi/repository/PessimisticLockContentRepository.java
  user-api/src/test/resources/application-test.yml
  user-api/src/test/resources/application.yml
  user-api/src/test/resources/logback-test.xml
Labels: 🔖 MEDIUM, ✅ TEST, 🌚 BE, 🏀 CW

#372 Revert "[TEST] 조회수 동시성 테스트"
  biengual-core/build.gradle
  biengual-core/src/testFixtures/java/com/biengual/core/domain/entity/content/ContentDomainFixture.java
  biengual-core/src/testFixtures/java/com/biengual/core/domain/entity/content/ContentEntityWithVersion.java
  user-api/build.gradle
  user-api/src/test/java/com/biengual/userapi/concurrency/SimpleConcurrencyTest.java
  user-api/src/test/java/com/biengual/userapi/config/TestJpaConfig.java
  user-api/src/test/java/com/biengual/userapi/config/TestQueryDslConfig.java
  user-api/src/test/java/com/biengual/userapi/config/TestRedisRedissonConfig.java
  user-api/src/test/java/com/biengual/userapi/repository/OptimisticLockContentRepository.java
  user-api/src/test/java/com/biengual/userapi/repository/PessimisticLockContentRepository.java
  user-api/src/test/resources/application-test.yml
  user-api/src/test/resources/application.yml
  user-api/src/test/resources/logback-test.xml
Labels: 🔖 CRITICAL, 🌚 BE, 🏀 CW

#368 [FEAT] 대시보드 첫화면에서 사용하는 최근 학습 컨텐츠 1개를 요약하여 보여주는 API 기능 개발
  biengual-core/src/main/java/com/biengual/core/response/status/DashboardServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/success/DashboardSuccessCode.java
  user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardReader.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardService.java
  user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetRecentLearningSummaryDto.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/swagger/SwaggerGetRecentLearningSummary.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/RecentLearningHistoryCustomRepository.java
Labels: ✨ FEAT, 🔖 HIGH, 🌚 BE, 🏀 CW

#370 [FEAT] 대시보드 - 유저 현재 포인트 조회 기능 개발
  biengual-core/src/main/java/com/biengual/core/response/status/DashboardServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/success/DashboardSuccessCode.java
  user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardReader.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardService.java
  user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetCurrentPointDto.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/swagger/SwaggerGetCurrentPoint.java
  user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningStoreImpl.java
Labels: ✨ FEAT, 🔖 HIGH, 🌚 BE, 🏀 CW

#374 [FEAT] 퀴즈 포인트 및 퀴즈 기록 기능 추가
  biengual-core/src/main/java/com/biengual/core/domain/entity/paymenthistory/PaymentContentHistoryEntity.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/questionhistory/QuestionHistoryEntity.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/user/UserEntity.java
  biengual-core/src/main/java/com/biengual/core/enums/PointReason.java
  user-api/src/main/java/com/biengual/userapi/ai/PerplexityApiClient.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/payment/domain/PaymentReader.java
  user-api/src/main/java/com/biengual/userapi/payment/domain/PaymentRepository.java
  user-api/src/main/java/com/biengual/userapi/payment/infrastructure/PaymentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/payment/infrastructure/PaymentStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/question/application/QuestionFacade.java
  user-api/src/main/java/com/biengual/userapi/question/application/QuestionServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/question/domain/QuestionCommand.java
  user-api/src/main/java/com/biengual/userapi/question/domain/QuestionInfo.java
  user-api/src/main/java/com/biengual/userapi/question/domain/QuestionReader.java
  user-api/src/main/java/com/biengual/userapi/question/domain/QuestionService.java
  user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/question/presentation/GetHintDto.java
  user-api/src/main/java/com/biengual/userapi/question/presentation/QuestionDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/question/presentation/QuestionPublicController.java
  user-api/src/main/java/com/biengual/userapi/questionhistory/domain/QuestionHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/questionhistory/domain/QuestionHistoryReader.java
  user-api/src/main/java/com/biengual/userapi/questionhistory/domain/QuestionHistoryRepository.java
  user-api/src/main/java/com/biengual/userapi/questionhistory/domain/QuestionHistoryStore.java
  user-api/src/main/java/com/biengual/userapi/questionhistory/infrastructure/QuestionHistoryReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/questionhistory/infrastructure/QuestionHistoryStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/validator/QuestionValidator.java
  user-api/src/main/resources/db/migration/V1.11.0__create.sql
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#377 [FEAT] 대시보드 - 월간 미션 달력 조회 기능 개발
  biengual-core/src/main/java/com/biengual/core/response/status/DashboardServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/success/DashboardSuccessCode.java
  user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardReader.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardService.java
  user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetMissionCalendarDto.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/swagger/SwaggerGetMissionCalendar.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/domain/MissionHistoryCustomRepository.java
Labels: ✨ FEAT, 🔖 HIGH, 🌚 BE, 🏀 CW

#379 [FEAT] 문제 조회 - 기능 수정 및 추가
  biengual-core/src/main/java/com/biengual/core/constant/RestrictionConstant.java
  biengual-core/src/main/java/com/biengual/core/response/error/code/QuestionErrorCode.java
  biengual-core/src/main/java/com/biengual/core/response/status/QuestionServiceStatus.java
  user-api/src/main/java/com/biengual/userapi/ai/PerplexityApiClient.java
  user-api/src/main/java/com/biengual/userapi/question/application/QuestionFacade.java
  user-api/src/main/java/com/biengual/userapi/question/application/QuestionServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/question/domain/QuestionCommand.java
  user-api/src/main/java/com/biengual/userapi/question/domain/QuestionReader.java
  user-api/src/main/java/com/biengual/userapi/question/domain/QuestionService.java
  user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/question/presentation/QuestionDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/question/presentation/QuestionPublicController.java
  user-api/src/main/java/com/biengual/userapi/questionhistory/domain/QuestionHistoryCustomRepository.java
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#380 [REFACTOR] 프론트 요청으로 인한 유저 스크랩 컨텐츠 조회 응답 구조 변경
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapInfo.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapResponseDto.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#382 [REFACTOR] 최근 미션 기록 리턴 값 최대 5일로 고정
  user-api/src/main/java/com/biengual/userapi/missionhistory/domain/MissionHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/missionhistory/presentation/MissionHistoryPublicController.java
Labels: 🐶 YR, 🔖 LOW, ⚒️ REFACTOR, 🌚 BE

#383 [REFACTOR] 프론트 요청으로 인한 컨텐츠 디테일 조회 응답에 curentLearningRate와 completedLearningRate 추가
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/RecentLearningHistoryCustomRepository.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#387 [FEAT] 대시보드 - 포인트 내역 조회 기능 개발
  biengual-core/src/main/java/com/biengual/core/response/status/DashboardServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/success/DashboardSuccessCode.java
  user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardReader.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardService.java
  user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetMonthlyPointHistoryDto.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/swagger/SwaggerGetMonthlyPointHistory.java
  user-api/src/main/java/com/biengual/userapi/pointhistory/domain/PointHistoryCustomRepository.java
Labels: ✨ FEAT, 🔖 HIGH, 🌚 BE, 🏀 CW

#388 [FEAT] 퀴즈 대시보드 - 월간 첫시도, 재시도 정답률 조회
  biengual-core/src/main/java/com/biengual/core/response/status/DashboardServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/success/DashboardSuccessCode.java
  user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardReader.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardService.java
  user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetQuestionSummaryDto.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/swagger/SwaggerGetQuestionSummary.java
  user-api/src/main/java/com/biengual/userapi/questionhistory/domain/QuestionHistoryCustomRepository.java
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#390 [HOTFIX] 문제 조회 시 맞춘 문제 검증 로직 오류 수정
  user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionReaderImpl.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#392 [REFACTOR] 대시보드 퀴즈 조회 내용 수정
  biengual-core/src/main/java/com/biengual/core/util/PeriodUtil.java
  user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardReader.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardService.java
  user-api/src/main/java/com/biengual/userapi/dashboard/infrastructure/DashboardReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/DashboardPublicController.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetQuestionSummaryDto.java
  user-api/src/main/java/com/biengual/userapi/questionhistory/domain/QuestionHistoryCustomRepository.java
Labels: 🐶 YR, 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE

#394 [BUGFIX] 최근 학습 내역과 카테고리별 학습 내역 기록 동시성 문제 해결
  biengual-core/src/main/java/com/biengual/core/annotation/RedisDistributedLock.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/category/CategoryEntity.java
  biengual-core/src/main/java/com/biengual/core/util/AopForTransaction.java
  biengual-core/src/main/java/com/biengual/core/util/CustomSpringELParser.java
  user-api/build.gradle
  user-api/src/main/java/com/biengual/userapi/aop/RedissonLockAspect.java
  user-api/src/main/java/com/biengual/userapi/config/RedissonConfig.java
  user-api/src/main/java/com/biengual/userapi/dashboard/application/DashboardServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/learning/application/LearningServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningStoreImpl.java
  user-api/src/test/java/com/biengual/userapi/UserApiApplicationTests.java
  user-api/src/test/java/com/biengual/userapi/controller/UserApiControllerTest.java
  user-api/src/test/java/com/biengual/userapi/domain/category/CategoryTestFixture.java
  user-api/src/test/java/com/biengual/userapi/domain/content/ContentTestFixture.java
  user-api/src/test/java/com/biengual/userapi/domain/learning/LearningConcurrencyTest.java
  user-api/src/test/java/com/biengual/userapi/domain/learning/LearningTestFixture.java
  user-api/src/test/java/com/biengual/userapi/domain/learning/TestCategoryLearningHistoryRepository.java
  user-api/src/test/java/com/biengual/userapi/domain/learning/TestRecentLearningHistoryRepository.java
  user-api/src/test/java/com/biengual/userapi/service/UserServiceTest.java
  user-api/src/test/resources/application-test.yml
  user-api/src/test/resources/application.yml
  user-api/src/test/resources/logback-test.xml
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#396 [BUGFIX] yml 파일 127.0.0.1 을 localhost로 변경
  user-api/src/main/resources/yml/application-dev.yml
  user-api/src/main/resources/yml/application-local.yml
  user-api/src/main/resources/yml/application-prod.yml
  user-api/src/test/resources/application-test.yml
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#397 [FIX] yml 파일 Redis host를 환경변수로 실제 인스턴스 서버 IP로 받게끔 변경
  user-api/src/main/resources/yml/application-dev.yml
  user-api/src/main/resources/yml/application-prod.yml
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#398 [BUGFIX] PointHistory의 balancePoint가 정상적으로 반영안되는 문제 해결
  biengual-core/src/main/java/com/biengual/core/domain/entity/pointhistory/PointHistoryEntity.java
  user-api/src/main/java/com/biengual/userapi/learning/application/LearningServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/point/domain/PointManager.java
  user-api/src/main/java/com/biengual/userapi/pointhistory/domain/PointHistoryStore.java
  user-api/src/main/java/com/biengual/userapi/pointhistory/infrastructure/PointHistoryStoreImpl.java
  user-api/src/test/java/com/biengual/userapi/common/util/ExecutorServiceUtil.java
  user-api/src/test/java/com/biengual/userapi/domain/learning/LearningConcurrencyTest.java
  user-api/src/test/java/com/biengual/userapi/domain/point/PointConcurrencyTest.java
  user-api/src/test/java/com/biengual/userapi/domain/point/TestPointHistoryRepository.java
  user-api/src/test/java/com/biengual/userapi/domain/user/UserTestFixture.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#401 [FEAT] 카테고리 학습 기록 기반 컨텐츠 추천
  biengual-core/src/main/java/com/biengual/core/domain/entity/learning/CategoryLearningHistoryEntity.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/recommender/CategoryRecommenderEntity.java
  biengual-core/src/main/java/com/biengual/core/response/status/RecommenderServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/success/RecommenderSuccessCode.java
  biengual-core/src/main/java/com/biengual/core/util/StringListConverter.java
  user-api/src/main/java/com/biengual/userapi/category/domain/CategoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/CategoryLearningHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningCommand.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningReader.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/RecentLearningHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/application/RecommenderServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/CategoryRecommenderRepository.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderInfo.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderService.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderStore.java
  user-api/src/main/java/com/biengual/userapi/recommender/infrastructure/RecommenderStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/GetPreviewDto.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/RecommenderApiController.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/RecommenderDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/RecommenderPublicController.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/swagger/SwaggerCategoryRecommender.java
  user-api/src/main/resources/db/migration/V1.12.0__alter.sql
  user-api/src/main/resources/db/migration/V1.12.1__create.sql
  user-api/src/main/resources/db/migration/V1.12.2__update.sql
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#405 [REFACTOR] 프론트 요청에 따라 본인 정보 수정 시 CategoryIds를 Optional하게 요청할 수 있게 수정
  biengual-core/src/main/java/com/biengual/core/constant/BadRequestMessageConstant.java
  user-api/src/main/java/com/biengual/userapi/user/application/UserFacade.java
  user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/user/presentation/UserPublicController.java
  user-api/src/main/java/com/biengual/userapi/user/presentation/UserRequestDto.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#407 [BUGFIX] ContentStatus를 반대로 체크하던 것을 수정
  biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentEntity.java
  user-api/src/main/java/com/biengual/userapi/validator/ContentValidator.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#409 [FEAT] 지난주 북마크 추천 저장 및 조회 기능 추가
  biengual-core/src/main/java/com/biengual/core/domain/entity/recommender/BookmarkRecommenderEntity.java
  biengual-core/src/main/java/com/biengual/core/response/status/RecommenderServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/success/RecommenderSuccessCode.java
  biengual-core/src/main/java/com/biengual/core/util/PeriodUtil.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkInfo.java
  user-api/src/main/java/com/biengual/userapi/bookmark/infrastructure/BookmarkReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/bookmark/presentation/BookmarkDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/crawling/application/TranslateApiClient.java
  user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/application/RecommenderServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/BookmarkRecommenderRepository.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderInfo.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderReader.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderService.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderStore.java
  user-api/src/main/java/com/biengual/userapi/recommender/infrastructure/RecommenderReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/infrastructure/RecommenderStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/GetPopularSentenceDto.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/RecommenderApiController.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/RecommenderDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/RecommenderPublicController.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/swagger/SwaggerBookmarkRecommender.java
  user-api/src/main/resources/db/migration/V1.15.0__create.sql
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#410 [HOTFIX] 프론트 요청에 따른 response 수정
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderInfo.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/GetPreviewDto.java
Labels: 🐶 YR, 🔖 LOW, ⚒️ REFACTOR, 🌚 BE

#413 [HOTFIX] 이전 response 수정 pr 에서 수정되지 않았던 constructor 수정
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#415 [REFACTOR] 카카오 로그인 시 받는 nickname 을 user 엔티티의 username으로 받도록 수정
  user-api/src/main/java/com/biengual/userapi/oauth2/info/KakaoUserInfo.java
  user-api/src/main/java/com/biengual/userapi/oauth2/info/NaverUserInfo.java
Labels: 🐶 YR, 🐞 BUGFIX, ⚒️ REFACTOR, 🌚 BE

#411 [FEAT] 집계된 ContentLevelFeedback에 대한 ContentLevel 선정 기능 추가 + 응답 Dto에 ContentLevel 추가
  biengual-core/src/main/java/com/biengual/core/constant/RestrictionConstant.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentEntity.java
  biengual-core/src/main/java/com/biengual/core/response/error/code/ContentErrorCode.java
  biengual-core/src/main/java/com/biengual/core/response/status/ContentServiceStatus.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentFacade.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentLevelFeedbackHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentStore.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentResponseDto.java
  user-api/src/main/java/com/biengual/userapi/dashboard/domain/DashboardInfo.java
  user-api/src/main/java/com/biengual/userapi/dashboard/presentation/dto/GetRecentLearningDto.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/RecentLearningHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/metadata/domain/MetadataStore.java
  user-api/src/main/java/com/biengual/userapi/metadata/infrastructure/MetadataStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/schedule/application/ScheduleServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/scrap/application/ScrapFacade.java
  user-api/src/main/java/com/biengual/userapi/scrap/domain/ScrapInfo.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapApiController.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapResponseDto.java
Labels: ✨ FEAT, 🔖 HIGH, 🌚 BE, 🏀 CW

#417 [HOTFIX] 프론트 요청 : 카테고리 매핑 변경, Unknown -> ETC
  biengual-core/src/main/java/com/biengual/core/constant/ServiceConstant.java
  user-api/src/main/resources/db/migration/V1.16.0__update.sql
Labels: 🐶 YR, 🔖 CRITICAL, ⚒️ REFACTOR, 🌚 BE

#420 [FEAT] 컨텐츠 타입에 따른 카테고리 조회
  user-api/src/main/java/com/biengual/userapi/category/application/CategoryServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/category/domain/CategoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/category/domain/CategoryReader.java
  user-api/src/main/java/com/biengual/userapi/category/domain/CategoryService.java
  user-api/src/main/java/com/biengual/userapi/category/infrastructure/CategoryReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/category/presentation/CategoryPublicController.java
Labels: ✨ FEAT, 🐶 YR, 🔖 HIGH, 🌚 BE

#423 [HOTFIX] 첫 로그인 시 카테고리 추천에서 랜덤으로 주기 위한 로직
  user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderCustomRepository.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#422 [REFACTOR] 로깅 고도화 1차
  biengual-core/src/main/java/com/biengual/core/response/error/GlobalExceptionHandler.java
  biengual-core/src/main/java/com/biengual/core/util/GlobalExceptionLogSchema.java
  biengual-core/src/main/java/com/biengual/core/util/RestControllerSuccessLogSchema.java
  user-api/src/main/java/com/biengual/userapi/aop/LoggingAspect.java
  user-api/src/main/java/com/biengual/userapi/config/HttpRequestFilterConfig.java
  user-api/src/main/java/com/biengual/userapi/config/ScheduleConfig.java
  user-api/src/main/java/com/biengual/userapi/filter/ReadableRequestWrapper.java
  user-api/src/main/java/com/biengual/userapi/filter/ReadableRequestWrapperFilter.java
  user-api/src/main/resources/logback.xml
Labels: ✨ FEAT, 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#428 DEV Into MAIN
  biengual-core/src/main/java/com/biengual/core/response/error/GlobalExceptionHandler.java
  biengual-core/src/main/java/com/biengual/core/util/GlobalExceptionLogSchema.java
  biengual-core/src/main/java/com/biengual/core/util/HttpServletRequestUtil.java
  biengual-core/src/main/java/com/biengual/core/util/RestControllerSuccessLogSchema.java
  user-api/src/main/java/com/biengual/userapi/aop/LoggingAspect.java
  user-api/src/main/java/com/biengual/userapi/config/HttpRequestFilterConfig.java
  user-api/src/main/java/com/biengual/userapi/config/ScheduleConfig.java
  user-api/src/main/java/com/biengual/userapi/filter/ReadableRequestWrapper.java
  user-api/src/main/java/com/biengual/userapi/filter/ReadableRequestWrapperFilter.java
  user-api/src/main/resources/logback.xml
Labels: 🪨 DEPLOY, 🌚 BE, 🏀 CW

#425 [HOTFIX] 의미없는 셔플 수정
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderCustomRepository.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 HIGH, 🌚 BE

#430 [HOTFIX] 북마크 추천 시스템 중복 업데이트 방지
  user-api/src/main/java/com/biengual/userapi/bookmark/domain/BookmarkCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/recommender/infrastructure/RecommenderStoreImpl.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#432 [HOTFIX] 컨텐츠 타입 별 카테고리 권한
  user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#435 [BUGFIX] 핸들링하지 않는 모든 예외처리에서 진짜 에러메시지도 최소 한번은 찍도록 수정
  biengual-core/src/main/java/com/biengual/core/response/error/GlobalExceptionHandler.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#437 DEV Into MAIN
  biengual-core/src/main/java/com/biengual/core/response/error/GlobalExceptionHandler.java
Labels: 🪨 DEPLOY, 🔖 HIGH, 🌚 BE, 🏀 CW

#441 [REFACTOR] 유저 정보 업데이트
  biengual-core/src/main/java/com/biengual/core/constant/BadRequestMessageConstant.java
  biengual-core/src/main/java/com/biengual/core/constant/RestrictionConstant.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/user/UserEntity.java
  biengual-core/src/main/java/com/biengual/core/response/error/code/UserErrorCode.java
  biengual-core/src/main/java/com/biengual/core/response/status/UserServiceStatus.java
  user-api/src/main/java/com/biengual/userapi/user/infrastructure/UserStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/user/presentation/UserRequestDto.java
  user-api/src/main/resources/db/migration/V1.17.0__update.sql
Labels: 🐶 YR, ⚒️ REFACTOR, 🌚 BE

#443 [REFACTOR] 프론트 요청에 따른 유료 컨텐츠 검증 로직 수정
  biengual-core/src/main/java/com/biengual/core/response/error/code/ContentErrorCode.java
  biengual-core/src/main/java/com/biengual/core/response/error/code/PointErrorCode.java
  biengual-core/src/main/java/com/biengual/core/response/status/ContentServiceStatus.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
Labels: 🐶 YR, 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE

#445 [HOTFIX] 포인트 지불했으나 isPointRequired 가 true 로 리턴되던 이슈 해결
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#447 [REFACTOR] 프론트 요청에 따른 카테고리 기반 추천 콘텐츠 응답에 calculatedLevel 추가
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderInfo.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/GetPreviewDto.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#449 [REFACTOR] 컨텐츠에 대한 문제 조회시 모든 문제를 정답을 맞췄다면 Exception 대신 빈배열을 보내도록 수정
  user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionReaderImpl.java
Labels: 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#452 [REFACTOR] 컨텐츠 상세 조회와 최신 컨텐츠 포인트 차감 로직 분리
  biengual-core/src/main/java/com/biengual/core/annotation/RedisDistributedLock.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentEntity.java
  biengual-core/src/main/java/com/biengual/core/response/error/code/PointErrorCode.java
  biengual-core/src/main/java/com/biengual/core/response/status/MetadataServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/status/PointServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/success/PointSuccessCode.java
  user-api/src/main/java/com/biengual/userapi/aop/RedissonLockAspect.java
  user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentReader.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/point/application/PointServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/point/domain/PointService.java
  user-api/src/main/java/com/biengual/userapi/point/presentation/PointPublicController.java
  user-api/src/main/java/com/biengual/userapi/validator/ContentValidator.java
  user-api/src/main/java/com/biengual/userapi/validator/PointValidator.java
  user-api/src/test/java/com/biengual/userapi/domain/content/ContentTestFixture.java
  user-api/src/test/java/com/biengual/userapi/domain/point/PointConcurrencyTest.java
Labels: ✨ FEAT, 🔖 HIGH, ⚒️ REFACTOR, ✅ TEST, 🌚 BE, 🏀 CW

#455 [REFACTOR] 스프링부트 이미지를 빌드할 때, 셀리니움 세팅 부분을 미리 만들어진 이미지에서 가져오도록 수정
  user-api/Dockerfile
  user-api/Dockerfile_Selenium
Labels: 🔖 LOW, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#456 [FEAT] OpenSearch 로컬 및 개발 서버 세팅, 기본 데이터 저장, 삭제, 검색 기능 추가
  biengual-core/build.gradle
  biengual-core/src/main/java/com/biengual/core/constant/ServiceConstant.java
  biengual-core/src/main/java/com/biengual/core/domain/document/content/ContentSearchDocument.java
  biengual-core/src/main/java/com/biengual/core/domain/document/content/script/CNNScript.java
  biengual-core/src/main/java/com/biengual/core/domain/document/content/script/YoutubeScript.java
  biengual-core/src/main/java/com/biengual/core/response/error/code/SearchContentErrorCode.java
  biengual-core/src/main/java/com/biengual/core/response/error/code/ServerError.java
  biengual-core/src/main/java/com/biengual/core/response/status/SearchContentServiceStatus.java
  docker-compose.yml
  user-api/build.gradle
  user-api/src/main/java/com/biengual/userapi/config/OpenSearchConfig.java
  user-api/src/main/java/com/biengual/userapi/config/OpenSearchContentConfig.java
  user-api/src/main/java/com/biengual/userapi/content/application/ContentServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCommand.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentInfo.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentReader.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentSearchRepository.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentSearchRepositoryImpl.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentService.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentStore.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentApiController.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentDtoMapper.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
  user-api/src/main/resources/yml/application-dev.yml
  user-api/src/main/resources/yml/application-local.yml
Labels: ✨ FEAT, 🐶 YR, 🔖 MEDIUM, 🌚 BE

#459 [BUGFIX] Question 조회 시 QuestionId 가 null로 오는 버그 해결
  user-api/src/main/java/com/biengual/userapi/question/domain/QuestionDocumentRepository.java
  user-api/src/main/java/com/biengual/userapi/question/domain/QuestionInfo.java
  user-api/src/main/java/com/biengual/userapi/question/infrastructure/QuestionReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/question/presentation/QuestionDtoMapper.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#460 [HOTFIX] OpenSearch DEV 연결 테스트
  user-api/src/main/java/com/biengual/userapi/config/OpenSearchConfig.java
  user-api/src/main/java/com/biengual/userapi/config/OpenSearchContentConfig.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE
