Repository Kernel360/F2-BIENGUAL-BE, pull requests merged in 2024-12, with the labels that each got.

#467 [BUGFIX] 북마크 추천 기능 서버 에러 해결
  biengual-core/src/main/java/com/biengual/core/util/PeriodUtil.java
  user-api/src/main/java/com/biengual/userapi/recommender/infrastructure/RecommenderReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/infrastructure/RecommenderStoreImpl.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#468 [BUGFIX]: #464 PR 에서 변경된 OpenSearch Port 명을 수정
  user-api/src/main/resources/yml/application-dev.yml
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#470 [BUGFIX] 카테고리 기반 컨텐츠 추천 기능 에러 해결
  biengual-core/src/main/java/com/biengual/core/util/StringListConverter.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderCustomRepository.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#464 [HOTFIX] OpenSearch 연결 문제 해결 - 포트 이슈
  user-api/src/main/java/com/biengual/userapi/config/OpenSearchContentConfig.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentReaderImpl.java
  user-api/src/main/resources/yml/application-local.yml
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#475 [HOTFIX] PROD OpenSearch index 추가
  biengual-core/src/main/java/com/biengual/core/constant/ServiceConstant.java
  user-api/src/main/java/com/biengual/userapi/config/OpenSearchContentConfig.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentSearchRepositoryImpl.java
  user-api/src/main/resources/yml/application-dev.yml
  user-api/src/main/resources/yml/application-local.yml
  user-api/src/main/resources/yml/application-prod.yml
Labels: 🐶 YR, 🪨 DEPLOY, 🔖 CRITICAL, ⚙️ SETTING, 🌚 BE

#477 [REFACTOR] S3, CDN 적용
  biengual-core/src/main/java/com/biengual/core/constant/ServiceConstant.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/content/ContentEntity.java
  biengual-core/src/main/java/com/biengual/core/response/error/code/ImageErrorCode.java
  biengual-core/src/main/java/com/biengual/core/response/status/ImageServiceStatus.java
  biengual-core/src/main/java/com/biengual/core/response/success/ImageSuccessCode.java
  biengual-core/src/main/java/com/biengual/core/swagger/SwaggerStringReturn.java
  docker-compose.yml
  user-api/build.gradle
  user-api/src/main/java/com/biengual/userapi/config/LocalStackConfig.java
  user-api/src/main/java/com/biengual/userapi/config/LocalStackImageConfig.java
  user-api/src/main/java/com/biengual/userapi/config/S3Config.java
  user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentApiController.java
  user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/image/application/ImageServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/image/domain/ImageReader.java
  user-api/src/main/java/com/biengual/userapi/image/domain/ImageService.java
  user-api/src/main/java/com/biengual/userapi/image/domain/ImageStore.java
  user-api/src/main/java/com/biengual/userapi/image/infrastructure/ImageReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/image/infrastructure/ImageStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/image/presentation/ImageApiController.java
  user-api/src/main/java/com/biengual/userapi/validator/ContentValidator.java
  user-api/src/main/resources/db/migration/V1.19.0__alter.sql
  user-api/src/main/resources/yml/application-dev.yml
  user-api/src/main/resources/yml/application-local.yml
Labels: 🐶 YR, 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE

#478 [HOTFIX] getImage method 의 URI 리턴에서 "https://" 삭제
  user-api/src/main/java/com/biengual/userapi/image/infrastructure/ImageReaderImpl.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 HIGH, 🌚 BE

#479 [HOTFIX] s3Url 적용 안된 곳 수정
  user-api/src/main/java/com/biengual/userapi/config/SecurityConfig.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/scrap/presentation/ScrapDtoMapper.java
Labels: 🐶 YR, 🔖 CRITICAL, ⚒️ REFACTOR, 🌚 BE

#480 [HOTFIX] s3Url 적용 안된 곳 수정
  user-api/src/main/java/com/biengual/userapi/learning/domain/RecentLearningHistoryCustomRepository.java
Labels: 🐶 YR, 🔖 CRITICAL, ⚒️ REFACTOR, 🌚 BE

#481 [REFACTOR] 사용하지 않는 PointDataMart 삭제 및 Spring Batch 비활성화
  biengual-core/src/main/java/com/biengual/core/domain/entity/pointdatamart/PointDataMart.java
  user-api/src/main/java/com/biengual/userapi/batch/BatchScheduler.java
  user-api/src/main/java/com/biengual/userapi/config/PointDataMartJobConfig.java
  user-api/src/main/java/com/biengual/userapi/pointdatamart/domain/PointDataMartRepository.java
  user-api/src/main/resources/application.yml
  user-api/src/main/resources/db/migration/V1.20.0__drop.sql
Labels: 🐶 YR, ⚒️ REFACTOR, 🌚 BE

#483 [REFACTOR] 크롤링 자동화
  biengual-core/src/main/java/com/biengual/core/annotation/WebCrawler.java
  biengual-core/src/main/java/com/biengual/core/constant/CrawlingAutomationConstant.java
  biengual-core/src/main/java/com/biengual/core/response/error/code/CrawlingErrorCode.java
  biengual-core/src/main/java/com/biengual/core/response/status/CrawlingServiceStatus.java
  user-api/build.gradle
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCommand.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentApiController.java
  user-api/src/main/java/com/biengual/userapi/crawling/application/JsoupWebCrawler.java
  user-api/src/main/java/com/biengual/userapi/crawling/application/SeleniumWebCrawler.java
  user-api/src/main/java/com/biengual/userapi/crawling/application/YoutubeApiClient.java
  user-api/src/main/java/com/biengual/userapi/crawling/domain/CrawlingReader.java
  user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/schedule/application/ScheduleServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/schedule/domain/ScheduleService.java
  user-api/src/main/java/com/biengual/userapi/validator/CrawlingValidator.java
Labels: 🐶 YR, 🔖 LOW, ⚒️ REFACTOR, 🌚 BE

#484 [REFACTOR] 카테고리 기반 컨텐츠 추천 로직 개선
  biengual-core/src/main/java/com/biengual/core/annotation/RedisCacheable.java
  biengual-core/src/main/java/com/biengual/core/constant/RedisUniqueKeyConstant.java
  biengual-core/src/main/java/com/biengual/core/constant/RestrictionConstant.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/learning/CategoryLearningProgressEntity.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/learning/CategoryLearningProgressId.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/learning/RecentLearningHistoryEntity.java
  biengual-core/src/main/java/com/biengual/core/domain/entity/recommender/CategoryRecommenderEntity.java
  biengual-core/src/main/java/com/biengual/core/domain/redis/RedisDto.java
  biengual-core/src/main/java/com/biengual/core/util/StringListConverter.java
  user-api/src/main/java/com/biengual/userapi/aop/RedisCacheAspect.java
  user-api/src/main/java/com/biengual/userapi/category/domain/CategoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/config/RedisConfig.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/application/LearningServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningCommand.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningReader.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/LearningStore.java
  user-api/src/main/java/com/biengual/userapi/learning/domain/RecentLearningHistoryCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/learning/infrastructure/LearningStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/application/ContentRecommender.java
  user-api/src/main/java/com/biengual/userapi/recommender/application/RecommenderServiceImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/CategoryLearningProgressCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/CategoryLearningProgressRepository.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/CategoryRecommenderRepository.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderCustomRepository.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderReader.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderService.java
  user-api/src/main/java/com/biengual/userapi/recommender/domain/RecommenderStore.java
  user-api/src/main/java/com/biengual/userapi/recommender/infrastructure/RecommenderReaderImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/infrastructure/RecommenderStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/recommender/presentation/RecommenderApiController.java
  user-api/src/main/java/com/biengual/userapi/validator/RecommenderValidator.java
  user-api/src/main/resources/db/migration/V1.18.0__create.sql
  user-api/src/main/resources/db/migration/V1.18.1__insert.sql
  user-api/src/main/resources/db/migration/V1.22.0__drop.sql
Labels: ✨ FEAT, 🔖 HIGH, ⚒️ REFACTOR, 🌚 BE, 🏀 CW

#485 [HOTFIX] YoutubeApiClient 에서 HttpHeaders 요청 시 배포 서버 에서 발생하는 NullPointException 에러 해결
  user-api/src/main/java/com/biengual/userapi/crawling/application/YoutubeApiClient.java
  user-api/src/main/java/com/biengual/userapi/schedule/application/ScheduleServiceImpl.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#486 [REFACTOR] imgUrl null 로 기본값 설정 후 이미지 확인하면서 최대값 찾도록 수정
  user-api/src/main/java/com/biengual/userapi/crawling/application/JsoupWebCrawler.java
Labels: 🐶 YR, 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE

#487 [REFACTOR] 문제 생성 자동화
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentStore.java
  user-api/src/main/java/com/biengual/userapi/content/infrastructure/ContentStoreImpl.java
  user-api/src/main/java/com/biengual/userapi/schedule/application/ScheduleServiceImpl.java
Labels: 🐶 YR, 🔖 MEDIUM, ⚒️ REFACTOR, 🌚 BE

#489 [FEAT] 프론트 요청으로 인한 Server Timing API를 위한 Filter 추가
  user-api/src/main/java/com/biengual/userapi/config/HttpRequestFilterConfig.java
  user-api/src/main/java/com/biengual/userapi/filter/ServerTimingFilter.java
Labels: ✨ FEAT, 🔖 HIGH, 🌚 BE, 🏀 CW

#491 [BUGFIX] Response Body가 사라진 문제 해결
  user-api/src/main/java/com/biengual/userapi/filter/ServerTimingFilter.java
Labels: 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE, 🏀 CW

#494 [REFACTOR] S3 배포 서버 설정 및 이미지 커스텀 예외 수정
  biengual-core/src/main/java/com/biengual/core/response/error/code/ImageErrorCode.java
  biengual-core/src/main/java/com/biengual/core/response/status/ImageServiceStatus.java
  user-api/src/main/java/com/biengual/userapi/image/infrastructure/ImageStoreImpl.java
  user-api/src/main/resources/yml/application-prod.yml
Labels: 🐶 YR, ⚒️ REFACTOR, 🌚 BE

#506 [HOTFIX] 유튜브 크롤링 시 쇼츠 제외
  biengual-core/src/main/java/com/biengual/core/constant/CrawlingAutomationConstant.java
  biengual-core/src/main/java/com/biengual/core/response/error/code/CrawlingErrorCode.java
  user-api/src/main/java/com/biengual/userapi/validator/CrawlingValidator.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#508 [HOTFIX] 카테고리 조회 시 모두 DEACTIVATED 이면 카테고리 조회 안 되도록 수정
  user-api/src/main/java/com/biengual/userapi/category/domain/CategoryCustomRepository.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 HIGH, 🌚 BE

#510 [HOTFIX] 카테고리 추천 시스템 - Index Out Of Bounds 해결
  user-api/src/main/java/com/biengual/userapi/recommender/application/ContentRecommender.java
Labels: 🐶 YR, 🐞 BUGFIX, 🌚 BE

#513 [HOTFIX] 검색어 20자 제한
  biengual-core/src/main/java/com/biengual/core/constant/BadRequestMessageConstant.java
  user-api/src/main/java/com/biengual/userapi/content/presentation/ContentPublicController.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 HIGH, 🌚 BE

#515 [HOTFIX] BookmarkRecommenderEntity en_detail, ko_detail 크기 변경
  biengual-core/src/main/java/com/biengual/core/domain/entity/recommender/BookmarkRecommenderEntity.java
  user-api/src/main/resources/db/migration/V1.23.0__alter.sql
Labels: 🐶 YR, 🐞 BUGFIX, 🌚 BE

#517 [HOTFIX] BookmarkRecommenderEntity end_of_week 날짜
  biengual-core/src/main/java/com/biengual/core/util/PeriodUtil.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#519 [REFACTOR] 미션 포인트 최종 확정
  biengual-core/src/main/java/com/biengual/core/enums/PointReason.java
Labels: 🐶 YR, 🔖 HIGH, 🌚 BE

#523 [HOTFIX] rss 에서 유튜브 컨텐츠 업데이트 url 받을 시 예외 처리 추가
  user-api/src/main/java/com/biengual/userapi/crawling/infrastructure/CrawlingReaderImpl.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#525 [HOTFIX] opensearch 노드 과부하 방지 설정 수정
  user-api/src/main/java/com/biengual/userapi/config/OpenSearchContentConfig.java
  user-api/src/main/java/com/biengual/userapi/content/domain/ContentSearchRepositoryImpl.java
Labels: 🐶 YR, 🐞 BUGFIX, 🔖 CRITICAL, 🌚 BE

#527 [HOTFIX] 더 이상 자동 크롤링 되지 않도록 수정
  user-api/src/main/java/com/biengual/userapi/schedule/application/ScheduleServiceImpl.java
Labels: 🐶 YR, 🔖 LOW, 🌚 BE
